SRCS= cs_appendtopic.c\
      cs_autoowner.c\
      cs_enforce.c\
      cs_helpop.c\
      cs_tban.c\
      hs_request.c\
      logchan.c\
      m_connect_flood.c\
      ns_maxemail.c\
      ns_noop_convert.c\
      os_forceid.c\
      os_info.c\
      os_notinchanlist.c
SUBS= bs_fantasy_ext\
      dummy