SRCS= bahamut.c\
      charybdis.c\
      dreamforge.c\
      hybrid.c\
      inspircd10.c\
      inspircd11.c\
      plexus2.c\
      plexus3.c\
      ptlink.c\
      rageircd.c\
      ratbox.c\
      shadowircd.c\
      solidircd.c\
      ultimate2.c\
      ultimate3.c\
      unreal31.c\
      unreal32.c\
      viagra.c
SUBS= dummy