#define LANG_NAME                        0
#define OS_ERR_MUSTBEROOT                1
#define STRFTIME_DATE_TIME_FORMAT        2
#define STRFTIME_LONG_DATE_FORMAT        3
#define STRFTIME_SHORT_DATE_FORMAT       4
#define STRFTIME_DAYS_SHORT              5
#define STRFTIME_DAYS_LONG               6
#define STRFTIME_MONTHS_SHORT            7
#define STRFTIME_MONTHS_LONG             8
#define COMMA_SPACE                      9
#define USER_RECORD_NOT_FOUND            10
#define UNKNOWN_COMMAND                  11
#define UNKNOWN_COMMAND_HELP             12
#define SYNTAX_ERROR                     13
#define MORE_INFO                        14
#define NO_HELP_AVAILABLE                15
#define OBSOLETE_COMMAND                 16
#define BAD_USERHOST_MASK                17
#define BAD_EXPIRY_TIME                  18
#define USERHOST_MASK_TOO_WIDE           19
#define SERVICE_OFFLINE                  20
#define READ_ONLY_MODE                   21
#define PASSWORD_INCORRECT               22
#define INVALID_TARGET                   23
#define ACCESS_DENIED                    24
#define PERMISSION_DENIED                25
#define RAW_DISABLED                     26
#define MORE_OBSCURE_PASSWORD            27
#define PASSWORD_TRUNCATED               28
#define NICK_NOT_REGISTERED              29
#define NICK_NOT_REGISTERED_HELP         30
#define NICK_X_IS_SERVICES               31
#define NICK_X_NOT_REGISTERED            32
#define NICK_X_IN_USE                    33
#define NICK_X_NOT_IN_USE                34
#define NICK_X_NOT_ON_CHAN               35
#define NICK_X_FORBIDDEN                 36
#define NICK_X_FORBIDDEN_OPER            37
#define NICK_X_ILLEGAL                   38
#define NICK_X_TRUNCATED                 39
#define NICK_X_SUSPENDED                 40
#define CHAN_X_NOT_REGISTERED            41
#define CHAN_X_NOT_IN_USE                42
#define CHAN_X_FORBIDDEN                 43
#define CHAN_X_FORBIDDEN_OPER            44
#define CHAN_X_SUSPENDED                 45
#define NICK_IDENTIFY_REQUIRED           46
#define CHAN_IDENTIFY_REQUIRED           47
#define MAIL_DISABLED                    48
#define MAIL_INVALID                     49
#define MAIL_X_INVALID                   50
#define MAIL_LATER                       51
#define MAIL_DELAYED                     52
#define NO_REASON                        53
#define UNKNOWN                          54
#define DURATION_DAY                     55
#define DURATION_DAYS                    56
#define DURATION_HOUR                    57
#define DURATION_HOURS                   58
#define DURATION_MINUTE                  59
#define DURATION_MINUTES                 60
#define DURATION_SECOND                  61
#define DURATION_SECONDS                 62
#define NO_EXPIRE                        63
#define EXPIRES_SOON                     64
#define EXPIRES_M                        65
#define EXPIRES_1M                       66
#define EXPIRES_HM                       67
#define EXPIRES_H1M                      68
#define EXPIRES_1HM                      69
#define EXPIRES_1H1M                     70
#define EXPIRES_D                        71
#define EXPIRES_1D                       72
#define END_OF_ANY_LIST                  73
#define LIST_INCORRECT_RANGE             74
#define CS_LIST_INCORRECT_RANGE          75
#define HELP_LIMIT_SERV_OPER             76
#define HELP_LIMIT_SERV_ADMIN            77
#define HELP_LIMIT_SERV_ROOT             78
#define HELP_LIMIT_IRC_OPER              79
#define HELP_LIMIT_HOST_SETTER           80
#define HELP_LIMIT_HOST_REMOVER          81
#define NICK_IS_REGISTERED               82
#define NICK_IS_SECURE                   83
#define NICK_MAY_NOT_BE_USED             84
#define FORCENICKCHANGE_IN_1_MINUTE      85
#define FORCENICKCHANGE_IN_20_SECONDS    86
#define FORCENICKCHANGE_NOW              87
#define FORCENICKCHANGE_CHANGING         88
#define NICK_REGISTER_SYNTAX             89
#define NICK_REGISTER_SYNTAX_EMAIL       90
#define NICK_REGISTRATION_DISABLED       91
#define NICK_REGISTRATION_FAILED         92
#define NICK_REG_PLEASE_WAIT             93
#define NICK_CANNOT_BE_REGISTERED        94
#define NICK_ALREADY_REGISTERED          95
#define NICK_REGISTERED                  96
#define NICK_REGISTERED_NO_MASK          97
#define NICK_PASSWORD_IS                 98
#define NICK_REG_DELAY                   99
#define NS_ADDNICK_SYNTAX                100
#define NS_ADDNICK_DISABLED              101
#define NS_ADDNICK_FAILED                102
#define NS_ADDNICK_PLEASE_WAIT           103
#define NS_ADDNICK_CHANGE_DISABLED       104
#define NS_ADDNICK_SAME                  105
#define NS_ADDNICK_TOO_MANY              106
#define NS_ADDNICK_SUCCESS               107
#define NICK_IDENTIFY_SYNTAX             108
#define NICK_IDENTIFY_FAILED             109
#define NICK_IDENTIFY_SUCCEEDED          110
#define NICK_IDENTIFY_EMAIL_REQUIRED     111
#define NICK_IDENTIFY_EMAIL_HOWTO        112
#define NICK_ALREADY_IDENTIFIED          113
#define NICK_UPDATE_SUCCESS              114
#define NICK_LOGOUT_SYNTAX               115
#define NICK_LOGOUT_SUCCEEDED            116
#define NICK_LOGOUT_X_SUCCEEDED          117
#define NICK_LOGOUT_SERVICESADMIN        118
#define NICK_DROP_DISABLED               119
#define NICK_DROPPED                     120
#define NICK_X_DROPPED                   121
#define NICK_SET_SYNTAX                  122
#define NICK_SET_SERVADMIN_SYNTAX        123
#define NICK_SET_DISABLED                124
#define NICK_SET_UNKNOWN_OPTION          125
#define NICK_SET_UNKNOWN_OPTION_OR_BAD_NICK 126
#define NICK_SET_OPTION_DISABLED         127
#define NICK_SET_DISPLAY_INVALID         128
#define NICK_SET_DISPLAY_CHANGED         129
#define NICK_SET_PASSWORD_FAILED         130
#define NICK_SET_PASSWORD_CHANGED        131
#define NICK_SET_PASSWORD_CHANGED_TO     132
#define NICK_SET_LANGUAGE_SYNTAX         133
#define NICK_SET_LANGUAGE_UNKNOWN        134
#define NICK_SET_LANGUAGE_CHANGED        135
#define NICK_SET_URL_CHANGED             136
#define NICK_SET_URL_UNSET               137
#define NICK_SET_EMAIL_CHANGED           138
#define NICK_SET_EMAIL_UNSET             139
#define NICK_SET_EMAIL_UNSET_IMPOSSIBLE  140
#define NICK_SET_ICQ_CHANGED             141
#define NICK_SET_ICQ_UNSET               142
#define NICK_SET_ICQ_INVALID             143
#define NICK_SET_GREET_CHANGED           144
#define NICK_SET_GREET_UNSET             145
#define NICK_SET_KILL_SYNTAX             146
#define NICK_SET_KILL_IMMED_SYNTAX       147
#define NICK_SET_KILL_ON                 148
#define NICK_SET_KILL_QUICK              149
#define NICK_SET_KILL_IMMED              150
#define NICK_SET_KILL_IMMED_DISABLED     151
#define NICK_SET_KILL_OFF                152
#define NICK_SET_SECURE_SYNTAX           153
#define NICK_SET_SECURE_ON               154
#define NICK_SET_SECURE_OFF              155
#define NICK_SET_PRIVATE_SYNTAX          156
#define NICK_SET_PRIVATE_ON              157
#define NICK_SET_PRIVATE_OFF             158
#define NICK_SET_HIDE_SYNTAX             159
#define NICK_SET_HIDE_EMAIL_ON           160
#define NICK_SET_HIDE_EMAIL_OFF          161
#define NICK_SET_HIDE_MASK_ON            162
#define NICK_SET_HIDE_MASK_OFF           163
#define NICK_SET_HIDE_QUIT_ON            164
#define NICK_SET_HIDE_QUIT_OFF           165
#define NICK_SET_HIDE_STATUS_ON          166
#define NICK_SET_HIDE_STATUS_OFF         167
#define NICK_SET_MSG_SYNTAX              168
#define NICK_SET_MSG_ON                  169
#define NICK_SET_MSG_OFF                 170
#define NICK_SET_AUTOOP_SYNTAX           171
#define NICK_SET_AUTOOP_ON               172
#define NICK_SET_AUTOOP_OFF              173
#define NICK_SASET_SYNTAX                174
#define NICK_SASET_DISABLED              175
#define NICK_SASET_UNKNOWN_OPTION        176
#define NICK_SASET_BAD_NICK              177
#define NICK_SASET_OPTION_DISABLED       178
#define NICK_SASET_DISPLAY_INVALID       179
#define NICK_SASET_DISPLAY_CHANGED       180
#define NICK_SASET_PASSWORD_FAILED       181
#define NICK_SASET_PASSWORD_CHANGED      182
#define NICK_SASET_PASSWORD_CHANGED_TO   183
#define NICK_SASET_URL_CHANGED           184
#define NICK_SASET_URL_UNSET             185
#define NICK_SASET_EMAIL_CHANGED         186
#define NICK_SASET_EMAIL_UNSET           187
#define NICK_SASET_EMAIL_UNSET_IMPOSSIBLE 188
#define NICK_SASET_ICQ_CHANGED           189
#define NICK_SASET_ICQ_UNSET             190
#define NICK_SASET_ICQ_INVALID           191
#define NICK_SASET_GREET_CHANGED         192
#define NICK_SASET_GREET_UNSET           193
#define NICK_SASET_KILL_SYNTAX           194
#define NICK_SASET_KILL_IMMED_SYNTAX     195
#define NICK_SASET_KILL_ON               196
#define NICK_SASET_KILL_QUICK            197
#define NICK_SASET_KILL_IMMED            198
#define NICK_SASET_KILL_IMMED_DISABLED   199
#define NICK_SASET_KILL_OFF              200
#define NICK_SASET_SECURE_SYNTAX         201
#define NICK_SASET_SECURE_ON             202
#define NICK_SASET_SECURE_OFF            203
#define NICK_SASET_PRIVATE_SYNTAX        204
#define NICK_SASET_PRIVATE_ON            205
#define NICK_SASET_PRIVATE_OFF           206
#define NICK_SASET_HIDE_SYNTAX           207
#define NICK_SASET_HIDE_EMAIL_ON         208
#define NICK_SASET_HIDE_EMAIL_OFF        209
#define NICK_SASET_HIDE_MASK_ON          210
#define NICK_SASET_HIDE_MASK_OFF         211
#define NICK_SASET_HIDE_QUIT_ON          212
#define NICK_SASET_HIDE_QUIT_OFF         213
#define NICK_SASET_HIDE_STATUS_ON        214
#define NICK_SASET_HIDE_STATUS_OFF       215
#define NICK_SASET_MSG_SYNTAX            216
#define NICK_SASET_MSG_ON                217
#define NICK_SASET_MSG_OFF               218
#define NICK_SASET_NOEXPIRE_SYNTAX       219
#define NICK_SASET_NOEXPIRE_ON           220
#define NICK_SASET_NOEXPIRE_OFF          221
#define NICK_SASET_AUTOOP_SYNTAX         222
#define NICK_SASET_AUTOOP_ON             223
#define NICK_SASET_AUTOOP_OFF            224
#define NS_ACCESS_SYNTAX                 225
#define NS_ACCESS_ALREADY_PRESENT        226
#define NS_ACCESS_LIMIT                  227
#define NS_ACCESS_ADDED                  228
#define NS_ACCESS_NOT_FOUND              229
#define NS_ACCESS_DELETED                230
#define NS_ACCESS_LIST                   231
#define NS_ACCESS_LIST_X                 232
#define NS_ACCESS_LIST_EMPTY             233
#define NS_ACCESS_LIST_X_EMPTY           234
#define NICK_STATUS_0                    235
#define NICK_STATUS_1                    236
#define NICK_STATUS_2                    237
#define NICK_STATUS_3                    238
#define NICK_INFO_SYNTAX                 239
#define NICK_INFO_REALNAME               240
#define NICK_INFO_SERVICES_OPER          241
#define NICK_INFO_SERVICES_ADMIN         242
#define NICK_INFO_SERVICES_ROOT          243
#define NICK_INFO_ADDRESS                244
#define NICK_INFO_ADDRESS_ONLINE         245
#define NICK_INFO_ADDRESS_ONLINE_NOHOST  246
#define NICK_INFO_TIME_REGGED            247
#define NICK_INFO_LAST_SEEN              248
#define NICK_INFO_LAST_QUIT              249
#define NICK_INFO_URL                    250
#define NICK_INFO_EMAIL                  251
#define NICK_INFO_VHOST                  252
#define NICK_INFO_VHOST2                 253
#define NICK_INFO_ICQ                    254
#define NICK_INFO_GREET                  255
#define NICK_INFO_OPTIONS                256
#define NICK_INFO_EXPIRE                 257
#define NICK_INFO_OPT_KILL               258
#define NICK_INFO_OPT_SECURE             259
#define NICK_INFO_OPT_PRIVATE            260
#define NICK_INFO_OPT_MSG                261
#define NICK_INFO_OPT_AUTOOP             262
#define NICK_INFO_OPT_NONE               263
#define NICK_INFO_NO_EXPIRE              264
#define NICK_INFO_FOR_MORE               265
#define NICK_INFO_SUSPENDED              266
#define NICK_INFO_SUSPENDED_NO_REASON    267
#define NICK_LIST_SYNTAX                 268
#define NICK_LIST_SERVADMIN_SYNTAX       269
#define NICK_LIST_HEADER                 270
#define NICK_LIST_RESULTS                271
#define NICK_ALIST_SYNTAX                272
#define NICK_ALIST_HEADER                273
#define NICK_ALIST_HEADER_X              274
#define NICK_ALIST_XOP_FORMAT            275
#define NICK_ALIST_ACCESS_FORMAT         276
#define NICK_ALIST_FOOTER                277
#define NS_MYNICKS_HEADER                278
#define NS_MYNICKS_HEADER_X              279
#define NS_MYNICKS_FOOTER                280
#define NS_MYNICKS_REPLY                 281
#define NS_MYNICKS_REPLY_ADMIN           282
#define NICK_RECOVER_SYNTAX              283
#define NICK_NO_RECOVER_SELF             284
#define NICK_RECOVERED                   285
#define NICK_RELEASE_SYNTAX              286
#define NICK_RELEASE_NOT_HELD            287
#define NICK_RELEASED                    288
#define NICK_GHOST_SYNTAX                289
#define NICK_NO_GHOST_SELF               290
#define NICK_GHOST_KILLED                291
#define NICK_GETPASS_SYNTAX              292
#define NICK_GETPASS_UNAVAILABLE         293
#define NICK_GETPASS_PASSWORD_IS         294
#define NICK_GETEMAIL_SYNTAX             295
#define NICK_GETEMAIL_EMAILS_ARE         296
#define NICK_GETEMAIL_NOT_USED           297
#define NICK_SENDPASS_SYNTAX             298
#define NICK_SENDPASS_UNAVAILABLE        299
#define NICK_SENDPASS_SUBJECT            300
#define NICK_SENDPASS_HEAD               301
#define NICK_SENDPASS_LINE_1             302
#define NICK_SENDPASS_LINE_2             303
#define NICK_SENDPASS_LINE_3             304
#define NICK_SENDPASS_LINE_4             305
#define NICK_SENDPASS_LINE_5             306
#define NICK_SENDPASS_OK                 307
#define NICK_SUSPEND_SYNTAX              308
#define NICK_SUSPEND_SUCCEEDED           309
#define NICK_SUSPEND_FAILED              310
#define NICK_UNSUSPEND_SYNTAX            311
#define NICK_UNSUSPEND_SUCCEEDED         312
#define NICK_UNSUSPEND_FAILED            313
#define NICK_FORBID_SYNTAX               314
#define NICK_FORBID_SYNTAX_REASON        315
#define NICK_FORBID_SUCCEEDED            316
#define NICK_FORBID_FAILED               317
#define NS_REQUESTED                     318
#define NICK_REG_RESENT                  319
#define NICK_REG_UNABLE                  320
#define NICK_IS_PREREG                   321
#define NICK_ENTER_REG_CODE              322
#define NICK_CONFIRM_NOT_FOUND           323
#define NICK_CONFIRM_INVALID             324
#define NICK_REG_MAIL_SUBJECT            325
#define NICK_REG_MAIL_HEAD               326
#define NICK_REG_MAIL_LINE_1             327
#define NICK_REG_MAIL_LINE_2             328
#define NICK_REG_MAIL_LINE_3             329
#define NICK_REG_MAIL_LINE_4             330
#define NICK_REG_MAIL_LINE_5             331
#define NICK_GETPASS_PASSCODE_IS         332
#define NICK_FORCE_REG                   333
#define CHAN_LEVEL_AUTOOP                334
#define CHAN_LEVEL_AUTOVOICE             335
#define CHAN_LEVEL_AUTOHALFOP            336
#define CHAN_LEVEL_AUTOPROTECT           337
#define CHAN_LEVEL_AUTODEOP              338
#define CHAN_LEVEL_NOJOIN                339
#define CHAN_LEVEL_INVITE                340
#define CHAN_LEVEL_AKICK                 341
#define CHAN_LEVEL_SET                   342
#define CHAN_LEVEL_CLEAR                 343
#define CHAN_LEVEL_UNBAN                 344
#define CHAN_LEVEL_OPDEOP                345
#define CHAN_LEVEL_ACCESS_LIST           346
#define CHAN_LEVEL_ACCESS_CHANGE         347
#define CHAN_LEVEL_MEMO                  348
#define CHAN_LEVEL_ASSIGN                349
#define CHAN_LEVEL_BADWORDS              350
#define CHAN_LEVEL_NOKICK                351
#define CHAN_LEVEL_FANTASIA              352
#define CHAN_LEVEL_SAY                   353
#define CHAN_LEVEL_GREET                 354
#define CHAN_LEVEL_VOICEME               355
#define CHAN_LEVEL_VOICE                 356
#define CHAN_LEVEL_GETKEY                357
#define CHAN_LEVEL_OPDEOPME              358
#define CHAN_LEVEL_HALFOPME              359
#define CHAN_LEVEL_HALFOP                360
#define CHAN_LEVEL_PROTECTME             361
#define CHAN_LEVEL_PROTECT               362
#define CHAN_LEVEL_KICKME                363
#define CHAN_LEVEL_KICK                  364
#define CHAN_LEVEL_SIGNKICK              365
#define CHAN_LEVEL_BANME                 366
#define CHAN_LEVEL_BAN                   367
#define CHAN_LEVEL_TOPIC                 368
#define CHAN_LEVEL_INFO                  369
#define CHAN_IS_REGISTERED               370
#define CHAN_NOT_ALLOWED_OP              371
#define CHAN_MAY_NOT_BE_USED             372
#define CHAN_NOT_ALLOWED_TO_JOIN         373
#define CHAN_X_INVALID                   374
#define CHAN_REGISTER_SYNTAX             375
#define CHAN_REGISTER_DISABLED           376
#define CHAN_REGISTER_NOT_LOCAL          377
#define CHAN_MUST_REGISTER_NICK          378
#define CHAN_MUST_IDENTIFY_NICK          379
#define CHAN_MAY_NOT_BE_REGISTERED       380
#define CHAN_ALREADY_REGISTERED          381
#define CHAN_MUST_BE_CHANOP              382
#define CHAN_REACHED_CHANNEL_LIMIT       383
#define CHAN_EXCEEDED_CHANNEL_LIMIT      384
#define CHAN_REGISTRATION_FAILED         385
#define CHAN_REGISTERED                  386
#define CHAN_PASSWORD_IS                 387
#define CHAN_REGISTER_NONE_CHANNEL       388
#define CHAN_SYMBOL_REQUIRED             389
#define CHAN_IDENTIFY_SYNTAX             390
#define CHAN_IDENTIFY_FAILED             391
#define CHAN_IDENTIFY_SUCCEEDED          392
#define CHAN_LOGOUT_SYNTAX               393
#define CHAN_LOGOUT_SERVADMIN_SYNTAX     394
#define CHAN_LOGOUT_SUCCEEDED            395
#define CHAN_LOGOUT_ALL_SUCCEEDED        396
#define CHAN_DROP_SYNTAX                 397
#define CHAN_DROP_DISABLED               398
#define CHAN_DROPPED                     399
#define CHAN_SET_SYNTAX                  400
#define CHAN_SET_DISABLED                401
#define CHAN_SET_UNKNOWN_OPTION          402
#define CHAN_SET_FOUNDER_TOO_MANY_CHANS  403
#define CHAN_FOUNDER_CHANGED             404
#define CHAN_SUCCESSOR_CHANGED           405
#define CHAN_SUCCESSOR_UNSET             406
#define CHAN_SUCCESSOR_IS_FOUNDER        407
#define CHAN_SET_PASSWORD_FAILED         408
#define CHAN_PASSWORD_CHANGED            409
#define CHAN_PASSWORD_CHANGED_TO         410
#define CHAN_DESC_CHANGED                411
#define CHAN_URL_CHANGED                 412
#define CHAN_URL_UNSET                   413
#define CHAN_EMAIL_CHANGED               414
#define CHAN_EMAIL_UNSET                 415
#define CHAN_ENTRY_MSG_CHANGED           416
#define CHAN_ENTRY_MSG_UNSET             417
#define CHAN_SET_BANTYPE_INVALID         418
#define CHAN_SET_BANTYPE_CHANGED         419
#define CHAN_SET_MLOCK_UNKNOWN_CHAR      420
#define CHAN_SET_MLOCK_IMPOSSIBLE_CHAR   421
#define CHAN_SET_MLOCK_L_REQUIRED        422
#define CHAN_SET_MLOCK_K_REQUIRED        423
#define CHAN_MLOCK_CHANGED               424
#define CHAN_SET_KEEPTOPIC_SYNTAX        425
#define CHAN_SET_KEEPTOPIC_ON            426
#define CHAN_SET_KEEPTOPIC_OFF           427
#define CHAN_SET_TOPICLOCK_SYNTAX        428
#define CHAN_SET_TOPICLOCK_ON            429
#define CHAN_SET_TOPICLOCK_OFF           430
#define CHAN_SET_PEACE_SYNTAX            431
#define CHAN_SET_PEACE_ON                432
#define CHAN_SET_PEACE_OFF               433
#define CHAN_SET_PRIVATE_SYNTAX          434
#define CHAN_SET_PRIVATE_ON              435
#define CHAN_SET_PRIVATE_OFF             436
#define CHAN_SET_SECUREOPS_SYNTAX        437
#define CHAN_SET_SECUREOPS_ON            438
#define CHAN_SET_SECUREOPS_OFF           439
#define CHAN_SET_SECUREFOUNDER_SYNTAX    440
#define CHAN_SET_SECUREFOUNDER_ON        441
#define CHAN_SET_SECUREFOUNDER_OFF       442
#define CHAN_SET_RESTRICTED_SYNTAX       443
#define CHAN_SET_RESTRICTED_ON           444
#define CHAN_SET_RESTRICTED_OFF          445
#define CHAN_SET_SECURE_SYNTAX           446
#define CHAN_SET_SECURE_ON               447
#define CHAN_SET_SECURE_OFF              448
#define CHAN_SET_SIGNKICK_SYNTAX         449
#define CHAN_SET_SIGNKICK_ON             450
#define CHAN_SET_SIGNKICK_LEVEL          451
#define CHAN_SET_SIGNKICK_OFF            452
#define CHAN_SET_OPNOTICE_SYNTAX         453
#define CHAN_SET_OPNOTICE_ON             454
#define CHAN_SET_OPNOTICE_OFF            455
#define CHAN_SET_XOP_SYNTAX              456
#define CHAN_SET_XOP_ON                  457
#define CHAN_SET_XOP_OFF                 458
#define CHAN_SET_NOEXPIRE_SYNTAX         459
#define CHAN_SET_NOEXPIRE_ON             460
#define CHAN_SET_NOEXPIRE_OFF            461
#define CHAN_XOP_REACHED_LIMIT           462
#define CHAN_XOP_LIST_FORMAT             463
#define CHAN_XOP_ACCESS                  464
#define CHAN_XOP_NOT_AVAILABLE           465
#define CHAN_AOP_SYNTAX                  466
#define CHAN_AOP_DISABLED                467
#define CHAN_AOP_NICKS_ONLY              468
#define CHAN_AOP_ADDED                   469
#define CHAN_AOP_MOVED                   470
#define CHAN_AOP_NO_SUCH_ENTRY           471
#define CHAN_AOP_NOT_FOUND               472
#define CHAN_AOP_NO_MATCH                473
#define CHAN_AOP_DELETED                 474
#define CHAN_AOP_DELETED_ONE             475
#define CHAN_AOP_DELETED_SEVERAL         476
#define CHAN_AOP_LIST_EMPTY              477
#define CHAN_AOP_LIST_HEADER             478
#define CHAN_AOP_CLEAR                   479
#define CHAN_HOP_SYNTAX                  480
#define CHAN_HOP_DISABLED                481
#define CHAN_HOP_NICKS_ONLY              482
#define CHAN_HOP_ADDED                   483
#define CHAN_HOP_MOVED                   484
#define CHAN_HOP_NO_SUCH_ENTRY           485
#define CHAN_HOP_NOT_FOUND               486
#define CHAN_HOP_NO_MATCH                487
#define CHAN_HOP_DELETED                 488
#define CHAN_HOP_DELETED_ONE             489
#define CHAN_HOP_DELETED_SEVERAL         490
#define CHAN_HOP_LIST_EMPTY              491
#define CHAN_HOP_LIST_HEADER             492
#define CHAN_HOP_CLEAR                   493
#define CHAN_SOP_SYNTAX                  494
#define CHAN_SOP_DISABLED                495
#define CHAN_SOP_NICKS_ONLY              496
#define CHAN_SOP_ADDED                   497
#define CHAN_SOP_MOVED                   498
#define CHAN_SOP_NO_SUCH_ENTRY           499
#define CHAN_SOP_NOT_FOUND               500
#define CHAN_SOP_NO_MATCH                501
#define CHAN_SOP_DELETED                 502
#define CHAN_SOP_DELETED_ONE             503
#define CHAN_SOP_DELETED_SEVERAL         504
#define CHAN_SOP_LIST_EMPTY              505
#define CHAN_SOP_LIST_HEADER             506
#define CHAN_SOP_CLEAR                   507
#define CHAN_VOP_SYNTAX                  508
#define CHAN_VOP_DISABLED                509
#define CHAN_VOP_NICKS_ONLY              510
#define CHAN_VOP_ADDED                   511
#define CHAN_VOP_MOVED                   512
#define CHAN_VOP_NO_SUCH_ENTRY           513
#define CHAN_VOP_NOT_FOUND               514
#define CHAN_VOP_NO_MATCH                515
#define CHAN_VOP_DELETED                 516
#define CHAN_VOP_DELETED_ONE             517
#define CHAN_VOP_DELETED_SEVERAL         518
#define CHAN_VOP_LIST_EMPTY              519
#define CHAN_VOP_LIST_HEADER             520
#define CHAN_VOP_CLEAR                   521
#define CHAN_ACCESS_SYNTAX               522
#define CHAN_ACCESS_XOP                  523
#define CHAN_ACCESS_XOP_HOP              524
#define CHAN_ACCESS_DISABLED             525
#define CHAN_ACCESS_LEVEL_NONZERO        526
#define CHAN_ACCESS_LEVEL_RANGE          527
#define CHAN_ACCESS_NICKS_ONLY           528
#define CHAN_ACCESS_REACHED_LIMIT        529
#define CHAN_ACCESS_LEVEL_UNCHANGED      530
#define CHAN_ACCESS_LEVEL_CHANGED        531
#define CHAN_ACCESS_ADDED                532
#define CHAN_ACCESS_NO_SUCH_ENTRY        533
#define CHAN_ACCESS_NOT_FOUND            534
#define CHAN_ACCESS_NO_MATCH             535
#define CHAN_ACCESS_DELETED              536
#define CHAN_ACCESS_DELETED_ONE          537
#define CHAN_ACCESS_DELETED_SEVERAL      538
#define CHAN_ACCESS_LIST_EMPTY           539
#define CHAN_ACCESS_LIST_HEADER          540
#define CHAN_ACCESS_LIST_FOOTER          541
#define CHAN_ACCESS_LIST_XOP_FORMAT      542
#define CHAN_ACCESS_LIST_AXS_FORMAT      543
#define CHAN_ACCESS_CLEAR                544
#define CHAN_AKICK_SYNTAX                545
#define CHAN_AKICK_DISABLED              546
#define CHAN_AKICK_ALREADY_EXISTS        547
#define CHAN_AKICK_REACHED_LIMIT         548
#define CHAN_AKICK_ADDED                 549
#define CHAN_AKICK_NO_SUCH_ENTRY         550
#define CHAN_AKICK_NOT_FOUND             551
#define CHAN_AKICK_NO_MATCH              552
#define CHAN_AKICK_STUCK                 553
#define CHAN_AKICK_UNSTUCK               554
#define CHAN_AKICK_DELETED               555
#define CHAN_AKICK_DELETED_ONE           556
#define CHAN_AKICK_DELETED_SEVERAL       557
#define CHAN_AKICK_LIST_EMPTY            558
#define CHAN_AKICK_LIST_HEADER           559
#define CHAN_AKICK_LIST_FORMAT           560
#define CHAN_AKICK_VIEW_FORMAT           561
#define CHAN_AKICK_VIEW_FORMAT_STUCK     562
#define CHAN_AKICK_ENFORCE_DONE          563
#define CHAN_AKICK_CLEAR                 564
#define CHAN_LEVELS_SYNTAX               565
#define CHAN_LEVELS_XOP                  566
#define CHAN_LEVELS_RANGE                567
#define CHAN_LEVELS_CHANGED              568
#define CHAN_LEVELS_UNKNOWN              569
#define CHAN_LEVELS_DISABLED             570
#define CHAN_LEVELS_LIST_HEADER          571
#define CHAN_LEVELS_LIST_DISABLED        572
#define CHAN_LEVELS_LIST_FOUNDER         573
#define CHAN_LEVELS_LIST_NORMAL          574
#define CHAN_LEVELS_RESET                575
#define CHAN_STATUS_SYNTAX               576
#define CHAN_STATUS_NOT_REGGED           577
#define CHAN_STATUS_FORBIDDEN            578
#define CHAN_STATUS_NOTONLINE            579
#define CHAN_STATUS_INFO                 580
#define CHAN_INFO_SYNTAX                 581
#define CHAN_INFO_HEADER                 582
#define CHAN_INFO_FOUNDER                583
#define CHAN_INFO_NO_FOUNDER             584
#define CHAN_INFO_SUCCESSOR              585
#define CHAN_INFO_NO_SUCCESSOR           586
#define CHAN_INFO_DESCRIPTION            587
#define CHAN_INFO_ENTRYMSG               588
#define CHAN_INFO_TIME_REGGED            589
#define CHAN_INFO_LAST_USED              590
#define CHAN_INFO_LAST_TOPIC             591
#define CHAN_INFO_TOPIC_SET_BY           592
#define CHAN_INFO_URL                    593
#define CHAN_INFO_EMAIL                  594
#define CHAN_INFO_BANTYPE                595
#define CHAN_INFO_OPTIONS                596
#define CHAN_INFO_OPT_KEEPTOPIC          597
#define CHAN_INFO_OPT_OPNOTICE           598
#define CHAN_INFO_OPT_PEACE              599
#define CHAN_INFO_OPT_PRIVATE            600
#define CHAN_INFO_OPT_RESTRICTED         601
#define CHAN_INFO_OPT_SECURE             602
#define CHAN_INFO_OPT_SECUREOPS          603
#define CHAN_INFO_OPT_SECUREFOUNDER      604
#define CHAN_INFO_OPT_SIGNKICK           605
#define CHAN_INFO_OPT_TOPICLOCK          606
#define CHAN_INFO_OPT_XOP                607
#define CHAN_INFO_OPT_NONE               608
#define CHAN_INFO_MODE_LOCK              609
#define CHAN_INFO_EXPIRE                 610
#define CHAN_INFO_NO_EXPIRE              611
#define CHAN_LIST_SYNTAX                 612
#define CHAN_LIST_SERVADMIN_SYNTAX       613
#define CHAN_LIST_HEADER                 614
#define CHAN_LIST_FORMAT                 615
#define CHAN_LIST_END                    616
#define CHAN_INVITE_SYNTAX               617
#define CHAN_UNBAN_SYNTAX                618
#define CHAN_UNBANNED                    619
#define CHAN_TOPIC_SYNTAX                620
#define CHAN_CLEAR_SYNTAX                621
#define CHAN_CLEARED_BANS                622
#define CHAN_CLEARED_EXCEPTS             623
#define CHAN_CLEARED_MODES               624
#define CHAN_CLEARED_OPS                 625
#define CHAN_CLEARED_HOPS                626
#define CHAN_CLEARED_VOICES              627
#define CHAN_CLEARED_USERS               628
#define CHAN_CLEARED_INVITES             629
#define CHAN_GETPASS_SYNTAX              630
#define CHAN_GETPASS_UNAVAILABLE         631
#define CHAN_GETPASS_PASSWORD_IS         632
#define CHAN_GETKEY_SYNTAX               633
#define CHAN_GETKEY_NOKEY                634
#define CHAN_GETKEY_KEY                  635
#define CHAN_SENDPASS_SYNTAX             636
#define CHAN_SENDPASS_UNAVAILABLE        637
#define CHAN_SENDPASS_SUBJECT            638
#define CHAN_SENDPASS_HEAD               639
#define CHAN_SENDPASS_LINE_1             640
#define CHAN_SENDPASS_LINE_2             641
#define CHAN_SENDPASS_LINE_3             642
#define CHAN_SENDPASS_LINE_4             643
#define CHAN_SENDPASS_LINE_5             644
#define CHAN_SENDPASS_OK                 645
#define CHAN_FORBID_SYNTAX               646
#define CHAN_FORBID_SYNTAX_REASON        647
#define CHAN_FORBID_SUCCEEDED            648
#define CHAN_FORBID_FAILED               649
#define CHAN_FORBID_REASON               650
#define CHAN_SUSPEND_SYNTAX              651
#define CHAN_SUSPEND_SYNTAX_REASON       652
#define CHAN_SUSPEND_SUCCEEDED           653
#define CHAN_SUSPEND_FAILED              654
#define CHAN_SUSPEND_REASON              655
#define CHAN_UNSUSPEND_SYNTAX            656
#define CHAN_UNSUSPEND_ERROR             657
#define CHAN_UNSUSPEND_SUCCEEDED         658
#define CHAN_UNSUSPEND_FAILED            659
#define CHAN_EXCEPTED                    660
#define MEMO_HAVE_NEW_MEMO               661
#define MEMO_HAVE_NEW_MEMOS              662
#define MEMO_TYPE_READ_LAST              663
#define MEMO_TYPE_READ_NUM               664
#define MEMO_TYPE_LIST_NEW               665
#define MEMO_AT_LIMIT                    666
#define MEMO_OVER_LIMIT                  667
#define MEMO_X_MANY_NOTICE               668
#define MEMO_X_ONE_NOTICE                669
#define MEMO_NEW_X_MEMO_ARRIVED          670
#define MEMO_NEW_MEMO_ARRIVED            671
#define MEMO_HAVE_NO_MEMOS               672
#define MEMO_X_HAS_NO_MEMOS              673
#define MEMO_DOES_NOT_EXIST              674
#define MEMO_LIST_NOT_FOUND              675
#define MEMO_SEND_SYNTAX                 676
#define MEMO_SEND_DISABLED               677
#define MEMO_SEND_PLEASE_WAIT            678
#define MEMO_X_GETS_NO_MEMOS             679
#define MEMO_X_HAS_TOO_MANY_MEMOS        680
#define MEMO_SENT                        681
#define MEMO_MASS_SENT                   682
#define MEMO_CANCEL_SYNTAX               683
#define MEMO_CANCEL_DISABLED             684
#define MEMO_CANCEL_NONE                 685
#define MEMO_CANCELLED                   686
#define MEMO_LIST_SYNTAX                 687
#define MEMO_HAVE_NO_NEW_MEMOS           688
#define MEMO_X_HAS_NO_NEW_MEMOS          689
#define MEMO_LIST_MEMOS                  690
#define MEMO_LIST_NEW_MEMOS              691
#define MEMO_LIST_CHAN_MEMOS             692
#define MEMO_LIST_CHAN_NEW_MEMOS         693
#define MEMO_LIST_HEADER                 694
#define MEMO_LIST_FORMAT                 695
#define MEMO_READ_SYNTAX                 696
#define MEMO_HEADER                      697
#define MEMO_CHAN_HEADER                 698
#define MEMO_TEXT                        699
#define MEMO_DEL_SYNTAX                  700
#define MEMO_DELETED_NONE                701
#define MEMO_DELETED_ONE                 702
#define MEMO_DELETED_SEVERAL             703
#define MEMO_DELETED_ALL                 704
#define MEMO_CHAN_DELETED_ALL            705
#define MEMO_SET_SYNTAX                  706
#define MEMO_SET_DISABLED                707
#define MEMO_SET_UNKNOWN_OPTION          708
#define MEMO_SET_NOTIFY_SYNTAX           709
#define MEMO_SET_NOTIFY_ON               710
#define MEMO_SET_NOTIFY_LOGON            711
#define MEMO_SET_NOTIFY_NEW              712
#define MEMO_SET_NOTIFY_OFF              713
#define MEMO_SET_NOTIFY_MAIL             714
#define MEMO_SET_NOTIFY_NOMAIL           715
#define MEMO_SET_NOTIFY_INVALIDMAIL      716
#define MEMO_SET_LIMIT_SYNTAX            717
#define MEMO_SET_LIMIT_SERVADMIN_SYNTAX  718
#define MEMO_SET_YOUR_LIMIT_FORBIDDEN    719
#define MEMO_SET_LIMIT_FORBIDDEN         720
#define MEMO_SET_YOUR_LIMIT_TOO_HIGH     721
#define MEMO_SET_LIMIT_TOO_HIGH          722
#define MEMO_SET_LIMIT_OVERFLOW          723
#define MEMO_SET_YOUR_LIMIT              724
#define MEMO_SET_YOUR_LIMIT_ZERO         725
#define MEMO_UNSET_YOUR_LIMIT            726
#define MEMO_SET_LIMIT                   727
#define MEMO_SET_LIMIT_ZERO              728
#define MEMO_UNSET_LIMIT                 729
#define MEMO_INFO_SYNTAX                 730
#define MEMO_INFO_SERVADMIN_SYNTAX       731
#define MEMO_INFO_NO_MEMOS               732
#define MEMO_INFO_MEMO                   733
#define MEMO_INFO_MEMO_UNREAD            734
#define MEMO_INFO_MEMOS                  735
#define MEMO_INFO_MEMOS_ONE_UNREAD       736
#define MEMO_INFO_MEMOS_SOME_UNREAD      737
#define MEMO_INFO_MEMOS_ALL_UNREAD       738
#define MEMO_INFO_LIMIT                  739
#define MEMO_INFO_HARD_LIMIT             740
#define MEMO_INFO_LIMIT_ZERO             741
#define MEMO_INFO_HARD_LIMIT_ZERO        742
#define MEMO_INFO_NO_LIMIT               743
#define MEMO_INFO_NOTIFY_OFF             744
#define MEMO_INFO_NOTIFY_ON              745
#define MEMO_INFO_NOTIFY_RECEIVE         746
#define MEMO_INFO_NOTIFY_SIGNON          747
#define MEMO_INFO_X_NO_MEMOS             748
#define MEMO_INFO_X_MEMO                 749
#define MEMO_INFO_X_MEMO_UNREAD          750
#define MEMO_INFO_X_MEMOS                751
#define MEMO_INFO_X_MEMOS_ONE_UNREAD     752
#define MEMO_INFO_X_MEMOS_SOME_UNREAD    753
#define MEMO_INFO_X_MEMOS_ALL_UNREAD     754
#define MEMO_INFO_X_LIMIT                755
#define MEMO_INFO_X_HARD_LIMIT           756
#define MEMO_INFO_X_NO_LIMIT             757
#define MEMO_INFO_X_NOTIFY_OFF           758
#define MEMO_INFO_X_NOTIFY_ON            759
#define MEMO_INFO_X_NOTIFY_RECEIVE       760
#define MEMO_INFO_X_NOTIFY_SIGNON        761
#define MEMO_MAIL_SUBJECT                762
#define MEMO_MAIL_TEXT1                  763
#define MEMO_MAIL_TEXT2                  764
#define MEMO_MAIL_TEXT3                  765
#define MEMO_RSEND_PLEASE_WAIT           766
#define MEMO_RSEND_DISABLED              767
#define MEMO_RSEND_SYNTAX                768
#define MEMO_RSEND_NICK_MEMO_TEXT        769
#define MEMO_RSEND_CHAN_MEMO_TEXT        770
#define MEMO_RSEND_USER_NOTIFICATION     771
#define MEMO_CHECK_SYNTAX                772
#define MEMO_CHECK_NOT_READ              773
#define MEMO_CHECK_READ                  774
#define MEMO_CHECK_NO_MEMO               775
#define MEMO_NO_RSEND_SELF               776
#define BOT_DOES_NOT_EXIST               777
#define BOT_NOT_ASSIGNED                 778
#define BOT_NOT_ON_CHANNEL               779
#define BOT_REASON_BADWORD               780
#define BOT_REASON_BADWORD_GENTLE        781
#define BOT_REASON_BOLD                  782
#define BOT_REASON_CAPS                  783
#define BOT_REASON_COLOR                 784
#define BOT_REASON_FLOOD                 785
#define BOT_REASON_REPEAT                786
#define BOT_REASON_REVERSE               787
#define BOT_REASON_UNDERLINE             788
#define BOT_SEEN_BOT                     789
#define BOT_SEEN_YOU                     790
#define BOT_SEEN_ON_CHANNEL              791
#define BOT_SEEN_ON_CHANNEL_AS           792
#define BOT_SEEN_ON                      793
#define BOT_SEEN_NEVER                   794
#define BOT_SEEN_UNKNOWN                 795
#define BOT_BOT_SYNTAX                   796
#define BOT_BOT_ALREADY_EXISTS           797
#define BOT_BOT_CREATION_FAILED          798
#define BOT_BOT_READONLY                 799
#define BOT_BOT_ADDED                    800
#define BOT_BOT_ANY_CHANGES              801
#define BOT_BOT_CHANGED                  802
#define BOT_BOT_DELETED                  803
#define BOT_BOTLIST_HEADER               804
#define BOT_BOTLIST_PRIVATE_HEADER       805
#define BOT_BOTLIST_FOOTER               806
#define BOT_BOTLIST_EMPTY                807
#define BOT_ASSIGN_SYNTAX                808
#define BOT_ASSIGN_READONLY              809
#define BOT_ASSIGN_ALREADY               810
#define BOT_ASSIGN_ASSIGNED              811
#define BOT_UNASSIGN_SYNTAX              812
#define BOT_UNASSIGN_UNASSIGNED          813
#define BOT_INFO_SYNTAX                  814
#define BOT_INFO_NOT_FOUND               815
#define BOT_INFO_BOT_HEADER              816
#define BOT_INFO_BOT_MASK                817
#define BOT_INFO_BOT_REALNAME            818
#define BOT_INFO_BOT_CREATED             819
#define BOT_INFO_BOT_USAGE               820
#define BOT_INFO_BOT_OPTIONS             821
#define BOT_INFO_OPT_PRIVATE             822
#define BOT_INFO_CHAN_HEADER             823
#define BOT_INFO_CHAN_BOT                824
#define BOT_INFO_CHAN_BOT_NONE           825
#define BOT_INFO_CHAN_KICK_BADWORDS      826
#define BOT_INFO_CHAN_KICK_BADWORDS_BAN  827
#define BOT_INFO_CHAN_KICK_BOLDS         828
#define BOT_INFO_CHAN_KICK_BOLDS_BAN     829
#define BOT_INFO_CHAN_KICK_CAPS_ON       830
#define BOT_INFO_CHAN_KICK_CAPS_BAN      831
#define BOT_INFO_CHAN_KICK_CAPS_OFF      832
#define BOT_INFO_CHAN_KICK_COLORS        833
#define BOT_INFO_CHAN_KICK_COLORS_BAN    834
#define BOT_INFO_CHAN_KICK_FLOOD_ON      835
#define BOT_INFO_CHAN_KICK_FLOOD_BAN     836
#define BOT_INFO_CHAN_KICK_FLOOD_OFF     837
#define BOT_INFO_CHAN_KICK_REPEAT_ON     838
#define BOT_INFO_CHAN_KICK_REPEAT_BAN    839
#define BOT_INFO_CHAN_KICK_REPEAT_OFF    840
#define BOT_INFO_CHAN_KICK_REVERSES      841
#define BOT_INFO_CHAN_KICK_REVERSES_BAN  842
#define BOT_INFO_CHAN_KICK_UNDERLINES    843
#define BOT_INFO_CHAN_KICK_UNDERLINES_BAN 844
#define BOT_INFO_ACTIVE                  845
#define BOT_INFO_INACTIVE                846
#define BOT_INFO_CHAN_OPTIONS            847
#define BOT_INFO_OPT_DONTKICKOPS         848
#define BOT_INFO_OPT_DONTKICKVOICES      849
#define BOT_INFO_OPT_FANTASY             850
#define BOT_INFO_OPT_GREET               851
#define BOT_INFO_OPT_NOBOT               852
#define BOT_INFO_OPT_SYMBIOSIS           853
#define BOT_INFO_OPT_NONE                854
#define BOT_SET_SYNTAX                   855
#define BOT_SET_DISABLED                 856
#define BOT_SET_UNKNOWN                  857
#define BOT_SET_DONTKICKOPS_SYNTAX       858
#define BOT_SET_DONTKICKOPS_ON           859
#define BOT_SET_DONTKICKOPS_OFF          860
#define BOT_SET_DONTKICKVOICES_SYNTAX    861
#define BOT_SET_DONTKICKVOICES_ON        862
#define BOT_SET_DONTKICKVOICES_OFF       863
#define BOT_SET_FANTASY_SYNTAX           864
#define BOT_SET_FANTASY_ON               865
#define BOT_SET_FANTASY_OFF              866
#define BOT_SET_GREET_SYNTAX             867
#define BOT_SET_GREET_ON                 868
#define BOT_SET_GREET_OFF                869
#define BOT_SET_NOBOT_SYNTAX             870
#define BOT_SET_NOBOT_ON                 871
#define BOT_SET_NOBOT_OFF                872
#define BOT_SET_PRIVATE_SYNTAX           873
#define BOT_SET_PRIVATE_ON               874
#define BOT_SET_PRIVATE_OFF              875
#define BOT_SET_SYMBIOSIS_SYNTAX         876
#define BOT_SET_SYMBIOSIS_ON             877
#define BOT_SET_SYMBIOSIS_OFF            878
#define BOT_KICK_SYNTAX                  879
#define BOT_KICK_DISABLED                880
#define BOT_KICK_UNKNOWN                 881
#define BOT_KICK_BAD_TTB                 882
#define BOT_KICK_BADWORDS_ON             883
#define BOT_KICK_BADWORDS_ON_BAN         884
#define BOT_KICK_BADWORDS_OFF            885
#define BOT_KICK_BOLDS_ON                886
#define BOT_KICK_BOLDS_ON_BAN            887
#define BOT_KICK_BOLDS_OFF               888
#define BOT_KICK_CAPS_ON                 889
#define BOT_KICK_CAPS_ON_BAN             890
#define BOT_KICK_CAPS_OFF                891
#define BOT_KICK_COLORS_ON               892
#define BOT_KICK_COLORS_ON_BAN           893
#define BOT_KICK_COLORS_OFF              894
#define BOT_KICK_FLOOD_ON                895
#define BOT_KICK_FLOOD_ON_BAN            896
#define BOT_KICK_FLOOD_OFF               897
#define BOT_KICK_REPEAT_ON               898
#define BOT_KICK_REPEAT_ON_BAN           899
#define BOT_KICK_REPEAT_OFF              900
#define BOT_KICK_REVERSES_ON             901
#define BOT_KICK_REVERSES_ON_BAN         902
#define BOT_KICK_REVERSES_OFF            903
#define BOT_KICK_UNDERLINES_ON           904
#define BOT_KICK_UNDERLINES_ON_BAN       905
#define BOT_KICK_UNDERLINES_OFF          906
#define BOT_BADWORDS_SYNTAX              907
#define BOT_BADWORDS_DISABLED            908
#define BOT_BADWORDS_REACHED_LIMIT       909
#define BOT_BADWORDS_ALREADY_EXISTS      910
#define BOT_BADWORDS_ADDED               911
#define BOT_BADWORDS_NO_SUCH_ENTRY       912
#define BOT_BADWORDS_NOT_FOUND           913
#define BOT_BADWORDS_NO_MATCH            914
#define BOT_BADWORDS_DELETED             915
#define BOT_BADWORDS_DELETED_ONE         916
#define BOT_BADWORDS_DELETED_SEVERAL     917
#define BOT_BADWORDS_LIST_EMPTY          918
#define BOT_BADWORDS_LIST_HEADER         919
#define BOT_BADWORDS_LIST_FORMAT         920
#define BOT_BADWORDS_CLEAR               921
#define BOT_SAY_SYNTAX                   922
#define BOT_ACT_SYNTAX                   923
#define BOT_EXCEPT                       924
#define BOT_BAD_NICK                     925
#define BOT_BAD_HOST                     926
#define BOT_BAD_IDENT                    927
#define BOT_LONG_IDENT                   928
#define OPER_BOUNCY_MODES                929
#define OPER_BOUNCY_MODES_U_LINE         930
#define OPER_GLOBAL_SYNTAX               931
#define OPER_STATS_UNKNOWN_OPTION        932
#define OPER_STATS_CURRENT_USERS         933
#define OPER_STATS_MAX_USERS             934
#define OPER_STATS_UPTIME_DHMS           935
#define OPER_STATS_UPTIME_1DHMS          936
#define OPER_STATS_UPTIME_HMS            937
#define OPER_STATS_UPTIME_HM1S           938
#define OPER_STATS_UPTIME_H1MS           939
#define OPER_STATS_UPTIME_H1M1S          940
#define OPER_STATS_UPTIME_1HMS           941
#define OPER_STATS_UPTIME_1HM1S          942
#define OPER_STATS_UPTIME_1H1MS          943
#define OPER_STATS_UPTIME_1H1M1S         944
#define OPER_STATS_UPTIME_MS             945
#define OPER_STATS_UPTIME_M1S            946
#define OPER_STATS_UPTIME_1MS            947
#define OPER_STATS_UPTIME_1M1S           948
#define OPER_STATS_BYTES_READ            949
#define OPER_STATS_BYTES_WRITTEN         950
#define OPER_STATS_USER_MEM              951
#define OPER_STATS_CHANNEL_MEM           952
#define OPER_STATS_GROUPS_MEM            953
#define OPER_STATS_ALIASES_MEM           954
#define OPER_STATS_CHANSERV_MEM          955
#define OPER_STATS_BOTSERV_MEM           956
#define OPER_STATS_OPERSERV_MEM          957
#define OPER_STATS_SESSIONS_MEM          958
#define OPER_STATS_AKILL_COUNT           959
#define OPER_STATS_AKILL_EXPIRE_DAYS     960
#define OPER_STATS_AKILL_EXPIRE_DAY      961
#define OPER_STATS_AKILL_EXPIRE_HOURS    962
#define OPER_STATS_AKILL_EXPIRE_HOUR     963
#define OPER_STATS_AKILL_EXPIRE_MINS     964
#define OPER_STATS_AKILL_EXPIRE_MIN      965
#define OPER_STATS_AKILL_EXPIRE_NONE     966
#define OPER_STATS_SGLINE_COUNT          967
#define OPER_STATS_SGLINE_EXPIRE_DAYS    968
#define OPER_STATS_SGLINE_EXPIRE_DAY     969
#define OPER_STATS_SGLINE_EXPIRE_HOURS   970
#define OPER_STATS_SGLINE_EXPIRE_HOUR    971
#define OPER_STATS_SGLINE_EXPIRE_MINS    972
#define OPER_STATS_SGLINE_EXPIRE_MIN     973
#define OPER_STATS_SGLINE_EXPIRE_NONE    974
#define OPER_STATS_SQLINE_COUNT          975
#define OPER_STATS_SQLINE_EXPIRE_DAYS    976
#define OPER_STATS_SQLINE_EXPIRE_DAY     977
#define OPER_STATS_SQLINE_EXPIRE_HOURS   978
#define OPER_STATS_SQLINE_EXPIRE_HOUR    979
#define OPER_STATS_SQLINE_EXPIRE_MINS    980
#define OPER_STATS_SQLINE_EXPIRE_MIN     981
#define OPER_STATS_SQLINE_EXPIRE_NONE    982
#define OPER_STATS_SZLINE_COUNT          983
#define OPER_STATS_SZLINE_EXPIRE_DAYS    984
#define OPER_STATS_SZLINE_EXPIRE_DAY     985
#define OPER_STATS_SZLINE_EXPIRE_HOURS   986
#define OPER_STATS_SZLINE_EXPIRE_HOUR    987
#define OPER_STATS_SZLINE_EXPIRE_MINS    988
#define OPER_STATS_SZLINE_EXPIRE_MIN     989
#define OPER_STATS_SZLINE_EXPIRE_NONE    990
#define OPER_STATS_RESET                 991
#define OPER_STATS_UPLINK_SERVER         992
#define OPER_STATS_UPLINK_CAPAB          993
#define OPER_STATS_UPLINK_SERVER_COUNT   994
#define OPER_MODE_SYNTAX                 995
#define OPER_UMODE_SYNTAX                996
#define OPER_UMODE_SUCCESS               997
#define OPER_UMODE_CHANGED               998
#define OPER_OLINE_SYNTAX                999
#define OPER_OLINE_SUCCESS               1000
#define OPER_OLINE_IRCOP                 1001
#define OPER_CLEARMODES_SYNTAX           1002
#define OPER_CLEARMODES_DONE             1003
#define OPER_CLEARMODES_ALL_DONE         1004
#define OPER_KICK_SYNTAX                 1005
#define OPER_SVSNICK_SYNTAX              1006
#define OPER_SVSNICK_NEWNICK             1007
#define OPER_ADMIN_SYNTAX                1008
#define OPER_ADMIN_SKELETON              1009
#define OPER_ADMIN_EXISTS                1010
#define OPER_ADMIN_REACHED_LIMIT         1011
#define OPER_ADMIN_ADDED                 1012
#define OPER_ADMIN_NOT_FOUND             1013
#define OPER_ADMIN_NO_MATCH              1014
#define OPER_ADMIN_DELETED               1015
#define OPER_ADMIN_DELETED_ONE           1016
#define OPER_ADMIN_DELETED_SEVERAL       1017
#define OPER_ADMIN_LIST_EMPTY            1018
#define OPER_ADMIN_LIST_HEADER           1019
#define OPER_ADMIN_LIST_FORMAT           1020
#define OPER_ADMIN_CLEAR                 1021
#define OPER_ADMIN_MOVED                 1022
#define OPER_OPER_SYNTAX                 1023
#define OPER_OPER_SKELETON               1024
#define OPER_OPER_EXISTS                 1025
#define OPER_OPER_REACHED_LIMIT          1026
#define OPER_OPER_ADDED                  1027
#define OPER_OPER_NOT_FOUND              1028
#define OPER_OPER_NO_MATCH               1029
#define OPER_OPER_DELETED                1030
#define OPER_OPER_DELETED_ONE            1031
#define OPER_OPER_DELETED_SEVERAL        1032
#define OPER_OPER_LIST_EMPTY             1033
#define OPER_OPER_LIST_HEADER            1034
#define OPER_OPER_LIST_FORMAT            1035
#define OPER_OPER_CLEAR                  1036
#define OPER_OPER_MOVED                  1037
#define OPER_AKILL_SYNTAX                1038
#define OPER_AKILL_EXISTS                1039
#define OPER_AKILL_ALREADY_COVERED       1040
#define OPER_AKILL_REACHED_LIMIT         1041
#define OPER_AKILL_NO_NICK               1042
#define OPER_AKILL_ADDED                 1043
#define OPER_AKILL_CHANGED               1044
#define OPER_AKILL_NOT_FOUND             1045
#define OPER_AKILL_NO_MATCH              1046
#define OPER_AKILL_DELETED               1047
#define OPER_AKILL_DELETED_ONE           1048
#define OPER_AKILL_DELETED_SEVERAL       1049
#define OPER_AKILL_LIST_EMPTY            1050
#define OPER_AKILL_LIST_HEADER           1051
#define OPER_AKILL_LIST_FORMAT           1052
#define OPER_AKILL_VIEW_HEADER           1053
#define OPER_AKILL_VIEW_FORMAT           1054
#define OPER_AKILL_CLEAR                 1055
#define OPER_CHANKILL_SYNTAX             1056
#define OPER_SGLINE_SYNTAX               1057
#define OPER_SGLINE_UNSUPPORTED          1058
#define OPER_SGLINE_EXISTS               1059
#define OPER_SGLINE_ALREADY_COVERED      1060
#define OPER_SGLINE_REACHED_LIMIT        1061
#define OPER_SGLINE_ADDED                1062
#define OPER_SGLINE_CHANGED              1063
#define OPER_SGLINE_NOT_FOUND            1064
#define OPER_SGLINE_NO_MATCH             1065
#define OPER_SGLINE_DELETED              1066
#define OPER_SGLINE_DELETED_ONE          1067
#define OPER_SGLINE_DELETED_SEVERAL      1068
#define OPER_SGLINE_LIST_EMPTY           1069
#define OPER_SGLINE_LIST_HEADER          1070
#define OPER_SGLINE_LIST_FORMAT          1071
#define OPER_SGLINE_VIEW_HEADER          1072
#define OPER_SGLINE_VIEW_FORMAT          1073
#define OPER_SGLINE_CLEAR                1074
#define OPER_SQLINE_SYNTAX               1075
#define OPER_SQLINE_CHANNELS_UNSUPPORTED 1076
#define OPER_SQLINE_EXISTS               1077
#define OPER_SQLINE_ALREADY_COVERED      1078
#define OPER_SQLINE_REACHED_LIMIT        1079
#define OPER_SQLINE_ADDED                1080
#define OPER_SQLINE_CHANGED              1081
#define OPER_SQLINE_NOT_FOUND            1082
#define OPER_SQLINE_NO_MATCH             1083
#define OPER_SQLINE_DELETED              1084
#define OPER_SQLINE_DELETED_ONE          1085
#define OPER_SQLINE_DELETED_SEVERAL      1086
#define OPER_SQLINE_LIST_EMPTY           1087
#define OPER_SQLINE_LIST_HEADER          1088
#define OPER_SQLINE_LIST_FORMAT          1089
#define OPER_SQLINE_VIEW_HEADER          1090
#define OPER_SQLINE_VIEW_FORMAT          1091
#define OPER_SQLINE_CLEAR                1092
#define OPER_SZLINE_SYNTAX               1093
#define OPER_SZLINE_UNSUPPORTED          1094
#define OPER_SZLINE_EXISTS               1095
#define OPER_SZLINE_ALREADY_COVERED      1096
#define OPER_SZLINE_REACHED_LIMIT        1097
#define OPER_SZLINE_ONLY_IPS             1098
#define OPER_SZLINE_ADDED                1099
#define OPER_SZLINE_CHANGED              1100
#define OPER_SZLINE_NOT_FOUND            1101
#define OPER_SZLINE_NO_MATCH             1102
#define OPER_SZLINE_DELETED              1103
#define OPER_SZLINE_DELETED_ONE          1104
#define OPER_SZLINE_DELETED_SEVERAL      1105
#define OPER_SZLINE_LIST_EMPTY           1106
#define OPER_SZLINE_LIST_HEADER          1107
#define OPER_SZLINE_LIST_FORMAT          1108
#define OPER_SZLINE_VIEW_HEADER          1109
#define OPER_SZLINE_VIEW_FORMAT          1110
#define OPER_SZLINE_CLEAR                1111
#define OPER_SET_SYNTAX                  1112
#define OPER_SET_IGNORE_ON               1113
#define OPER_SET_IGNORE_OFF              1114
#define OPER_SET_IGNORE_ERROR            1115
#define OPER_SET_READONLY_ON             1116
#define OPER_SET_READONLY_OFF            1117
#define OPER_SET_READONLY_ERROR          1118
#define OPER_SET_LOGCHAN_ON              1119
#define OPER_SET_LOGCHAN_OFF             1120
#define OPER_SET_LOGCHAN_ERROR           1121
#define OPER_SET_DEBUG_ON                1122
#define OPER_SET_DEBUG_OFF               1123
#define OPER_SET_DEBUG_LEVEL             1124
#define OPER_SET_DEBUG_ERROR             1125
#define OPER_SET_NOEXPIRE_ON             1126
#define OPER_SET_NOEXPIRE_OFF            1127
#define OPER_SET_NOEXPIRE_ERROR          1128
#define OPER_SET_UNKNOWN_OPTION          1129
#define OPER_SET_SQL_ON                  1130
#define OPER_SET_SQL_OFF                 1131
#define OPER_SET_SQL_ERROR               1132
#define OPER_SET_SQL_ERROR_INIT          1133
#define OPER_SET_SQL_ERROR_DISABLED      1134
#define OPER_SET_LIST_OPTION_ON          1135
#define OPER_SET_LIST_OPTION_OFF         1136
#define OPER_NOOP_SYNTAX                 1137
#define OPER_NOOP_SET                    1138
#define OPER_NOOP_REVOKE                 1139
#define OPER_JUPE_SYNTAX                 1140
#define OPER_JUPE_HOST_ERROR             1141
#define OPER_RAW_SYNTAX                  1142
#define OPER_UPDATING                    1143
#define OPER_RELOAD                      1144
#define OPER_CANNOT_RESTART              1145
#define OPER_IGNORE_SYNTAX               1146
#define OPER_IGNORE_VALID_TIME           1147
#define OPER_IGNORE_TIME_DONE            1148
#define OPER_IGNORE_PERM_DONE            1149
#define OPER_IGNORE_DEL_DONE             1150
#define OPER_IGNORE_LIST                 1151
#define OPER_IGNORE_LIST_NOMATCH         1152
#define OPER_IGNORE_LIST_EMPTY           1153
#define OPER_IGNORE_LIST_CLEARED         1154
#define OPER_KILLCLONES_SYNTAX           1155
#define OPER_KILLCLONES_UNKNOWN_NICK     1156
#define OPER_CHANLIST_HEADER             1157
#define OPER_CHANLIST_HEADER_USER        1158
#define OPER_CHANLIST_RECORD             1159
#define OPER_CHANLIST_END                1160
#define OPER_USERLIST_HEADER             1161
#define OPER_USERLIST_HEADER_CHAN        1162
#define OPER_USERLIST_RECORD             1163
#define OPER_USERLIST_END                1164
#define OPER_SUPER_ADMIN_ON              1165
#define OPER_SUPER_ADMIN_OFF             1166
#define OPER_SUPER_ADMIN_SYNTAX          1167
#define OPER_SUPER_ADMIN_WALL_ON         1168
#define OPER_SUPER_ADMIN_WALL_OFF        1169
#define OPER_SUPER_ADMIN_ONLY            1170
#define OPER_STAFF_LIST_HEADER           1171
#define OPER_STAFF_FORMAT                1172
#define OPER_STAFF_AFORMAT               1173
#define OPER_DEFCON_SYNTAX               1174
#define OPER_DEFCON_DENIED               1175
#define OPER_DEFCON_NO_CONF              1176
#define OPER_DEFCON_CHANGED              1177
#define OPER_DEFCON_WALL                 1178
#define DEFCON_GLOBAL                    1179
#define OPER_MODULE_LOADED               1180
#define OPER_MODULE_UNLOADED             1181
#define OPER_MODULE_LOAD_FAIL            1182
#define OPER_MODULE_REMOVE_FAIL          1183
#define OPER_MODULE_NO_UNLOAD            1184
#define OPER_MODULE_LOAD_SYNTAX          1185
#define OPER_MODULE_UNLOAD_SYNTAX        1186
#define OPER_MODULE_LIST_HEADER          1187
#define OPER_MODULE_LIST                 1188
#define OPER_MODULE_LIST_FOOTER          1189
#define OPER_MODULE_INFO_LIST            1190
#define OPER_MODULE_CMD_LIST             1191
#define OPER_MODULE_MSG_LIST             1192
#define OPER_MODULE_NO_LIST              1193
#define OPER_MODULE_NO_INFO              1194
#define OPER_MODULE_INFO_SYNTAX          1195
#define MODULE_HELP_HEADER               1196
#define OPER_EXCEPTION_SYNTAX            1197
#define OPER_EXCEPTION_ADD_SYNTAX        1198
#define OPER_EXCEPTION_DEL_SYNTAX        1199
#define OPER_EXCEPTION_MOVE_SYNTAX       1200
#define OPER_EXCEPTION_DISABLED          1201
#define OPER_EXCEPTION_ALREADY_PRESENT   1202
#define OPER_EXCEPTION_TOO_MANY          1203
#define OPER_EXCEPTION_ADDED             1204
#define OPER_EXCEPTION_MOVED             1205
#define OPER_EXCEPTION_NO_SUCH_ENTRY     1206
#define OPER_EXCEPTION_NOT_FOUND         1207
#define OPER_EXCEPTION_NO_MATCH          1208
#define OPER_EXCEPTION_DELETED           1209
#define OPER_EXCEPTION_DELETED_ONE       1210
#define OPER_EXCEPTION_DELETED_SEVERAL   1211
#define OPER_EXCEPTION_LIST_HEADER       1212
#define OPER_EXCEPTION_LIST_FORMAT       1213
#define OPER_EXCEPTION_LIST_COLHEAD      1214
#define OPER_EXCEPTION_VIEW_FORMAT       1215
#define OPER_EXCEPTION_INVALID_LIMIT     1216
#define OPER_EXCEPTION_INVALID_HOSTMASK  1217
#define OPER_EXCEPTION_EXISTS            1218
#define OPER_EXCEPTION_CHANGED           1219
#define OPER_SESSION_SYNTAX              1220
#define OPER_SESSION_LIST_SYNTAX         1221
#define OPER_SESSION_VIEW_SYNTAX         1222
#define OPER_SESSION_DISABLED            1223
#define OPER_SESSION_INVALID_THRESHOLD   1224
#define OPER_SESSION_NOT_FOUND           1225
#define OPER_SESSION_LIST_HEADER         1226
#define OPER_SESSION_LIST_COLHEAD        1227
#define OPER_SESSION_LIST_FORMAT         1228
#define OPER_SESSION_VIEW_FORMAT         1229
#define OPER_HELP_EXCEPTION              1230
#define OPER_HELP_SESSION                1231
#define OPER_HELP_STAFF                  1232
#define OPER_HELP_DEFCON                 1233
#define OPER_HELP_DEFCON_NO_NEW_CHANNELS 1234
#define OPER_HELP_DEFCON_NO_NEW_NICKS    1235
#define OPER_HELP_DEFCON_NO_MLOCK_CHANGE 1236
#define OPER_HELP_DEFCON_FORCE_CHAN_MODES 1237
#define OPER_HELP_DEFCON_REDUCE_SESSION  1238
#define OPER_HELP_DEFCON_NO_NEW_CLIENTS  1239
#define OPER_HELP_DEFCON_OPER_ONLY       1240
#define OPER_HELP_DEFCON_SILENT_OPER_ONLY 1241
#define OPER_HELP_DEFCON_AKILL_NEW_CLIENTS 1242
#define OPER_HELP_DEFCON_NO_NEW_MEMOS    1243
#define OPER_HELP_CHANKILL               1244
#define NEWS_LOGON_TEXT                  1245
#define NEWS_OPER_TEXT                   1246
#define NEWS_RANDOM_TEXT                 1247
#define NEWS_LOGON_SYNTAX                1248
#define NEWS_LOGON_LIST_HEADER           1249
#define NEWS_LOGON_LIST_ENTRY            1250
#define NEWS_LOGON_LIST_NONE             1251
#define NEWS_LOGON_ADD_SYNTAX            1252
#define NEWS_LOGON_ADD_FULL              1253
#define NEWS_LOGON_ADDED                 1254
#define NEWS_LOGON_DEL_SYNTAX            1255
#define NEWS_LOGON_DEL_NOT_FOUND         1256
#define NEWS_LOGON_DELETED               1257
#define NEWS_LOGON_DEL_NONE              1258
#define NEWS_LOGON_DELETED_ALL           1259
#define NEWS_OPER_SYNTAX                 1260
#define NEWS_OPER_LIST_HEADER            1261
#define NEWS_OPER_LIST_ENTRY             1262
#define NEWS_OPER_LIST_NONE              1263
#define NEWS_OPER_ADD_SYNTAX             1264
#define NEWS_OPER_ADD_FULL               1265
#define NEWS_OPER_ADDED                  1266
#define NEWS_OPER_DEL_SYNTAX             1267
#define NEWS_OPER_DEL_NOT_FOUND          1268
#define NEWS_OPER_DELETED                1269
#define NEWS_OPER_DEL_NONE               1270
#define NEWS_OPER_DELETED_ALL            1271
#define NEWS_RANDOM_SYNTAX               1272
#define NEWS_RANDOM_LIST_HEADER          1273
#define NEWS_RANDOM_LIST_ENTRY           1274
#define NEWS_RANDOM_LIST_NONE            1275
#define NEWS_RANDOM_ADD_SYNTAX           1276
#define NEWS_RANDOM_ADD_FULL             1277
#define NEWS_RANDOM_ADDED                1278
#define NEWS_RANDOM_DEL_SYNTAX           1279
#define NEWS_RANDOM_DEL_NOT_FOUND        1280
#define NEWS_RANDOM_DELETED              1281
#define NEWS_RANDOM_DEL_NONE             1282
#define NEWS_RANDOM_DELETED_ALL          1283
#define NEWS_HELP_LOGON                  1284
#define NEWS_HELP_OPER                   1285
#define NEWS_HELP_RANDOM                 1286
#define HELP_HELP                        1287
#define HELP_HELP_BOT                    1288
#define HELP_HELP_HOST                   1289
#define NICK_HELP_CMD_CONFIRM            1290
#define NICK_HELP_CMD_RESEND             1291
#define NICK_HELP_CMD_REGISTER           1292
#define NS_HELP_CMD_ADDNICK              1293
#define NICK_HELP_CMD_IDENTIFY           1294
#define NS_HELP_CMD_ACCESS               1295
#define NICK_HELP_CMD_SET                1296
#define NICK_HELP_CMD_SASET              1297
#define NICK_HELP_CMD_DROP               1298
#define NICK_HELP_CMD_RECOVER            1299
#define NICK_HELP_CMD_RELEASE            1300
#define NICK_HELP_CMD_SENDPASS           1301
#define NICK_HELP_CMD_GHOST              1302
#define NICK_HELP_CMD_ALIST              1303
#define NS_HELP_CMD_MYNICKS              1304
#define NICK_HELP_CMD_INFO               1305
#define NICK_HELP_CMD_LIST               1306
#define NICK_HELP_CMD_LOGOUT             1307
#define NICK_HELP_CMD_STATUS             1308
#define NICK_HELP_CMD_UPDATE             1309
#define NICK_HELP_CMD_GETPASS            1310
#define NICK_HELP_CMD_GETEMAIL           1311
#define NICK_HELP_CMD_FORBID             1312
#define NICK_HELP_CMD_SUSPEND            1313
#define NICK_HELP_CMD_UNSUSPEND          1314
#define NICK_HELP                        1315
#define NICK_HELP_FOOTER                 1316
#define NICK_HELP_EXPIRES                1317
#define NICK_HELP_REGISTER               1318
#define NS_HELP_ADDNICK                  1319
#define NICK_HELP_IDENTIFY               1320
#define NICK_HELP_UPDATE                 1321
#define NICK_HELP_LOGOUT                 1322
#define NICK_HELP_DROP                   1323
#define NS_HELP_ACCESS                   1324
#define NICK_HELP_SET                    1325
#define NICK_HELP_SET_DISPLAY            1326
#define NICK_HELP_SET_PASSWORD           1327
#define NICK_HELP_SET_LANGUAGE           1328
#define NICK_HELP_SET_URL                1329
#define NICK_HELP_SET_EMAIL              1330
#define NICK_HELP_SET_ICQ                1331
#define NICK_HELP_SET_GREET              1332
#define NICK_HELP_SET_KILL               1333
#define NICK_HELP_SET_SECURE             1334
#define NICK_HELP_SET_PRIVATE            1335
#define NICK_HELP_SET_HIDE               1336
#define NICK_HELP_SET_MSG                1337
#define NICK_HELP_SET_AUTOOP             1338
#define NICK_HELP_SASET                  1339
#define NICK_HELP_SASET_DISPLAY          1340
#define NICK_HELP_SASET_PASSWORD         1341
#define NICK_HELP_SASET_URL              1342
#define NICK_HELP_SASET_EMAIL            1343
#define NICK_HELP_SASET_ICQ              1344
#define NICK_HELP_SASET_GREET            1345
#define NICK_HELP_SASET_KILL             1346
#define NICK_HELP_SASET_SECURE           1347
#define NICK_HELP_SASET_PRIVATE          1348
#define NICK_HELP_SASET_HIDE             1349
#define NICK_HELP_SASET_MSG              1350
#define NICK_HELP_SASET_NOEXPIRE         1351
#define NICK_HELP_SASET_AUTOOP           1352
#define NICK_HELP_RECOVER                1353
#define NICK_HELP_RELEASE                1354
#define NICK_HELP_GHOST                  1355
#define NICK_HELP_INFO                   1356
#define NICK_HELP_LIST                   1357
#define NICK_HELP_ALIST                  1358
#define NS_HELP_MYNICKS                  1359
#define NICK_HELP_STATUS                 1360
#define NICK_HELP_SENDPASS               1361
#define NICK_HELP_CONFIRM                1362
#define NICK_SERVADMIN_HELP              1363
#define NICK_SERVADMIN_HELP_LOGOUT       1364
#define NICK_SERVADMIN_HELP_DROP         1365
#define NICK_SERVADMIN_HELP_INFO         1366
#define NICK_SERVADMIN_HELP_LIST         1367
#define NICK_SERVADMIN_HELP_ALIST        1368
#define NS_ADMIN_HELP_MYNICKS            1369
#define NICK_SERVADMIN_HELP_GETPASS      1370
#define NICK_SERVADMIN_HELP_GETEMAIL     1371
#define NICK_SERVADMIN_HELP_FORBID       1372
#define NICK_SERVADMIN_HELP_SUSPEND      1373
#define NICK_SERVADMIN_HELP_UNSUSPEND    1374
#define CHAN_HELP_CMD_GETPASS            1375
#define CHAN_HELP_CMD_FORBID             1376
#define CHAN_HELP_CMD_SUSPEND            1377
#define CHAN_HELP_CMD_UNSUSPEND          1378
#define CHAN_HELP_CMD_STATUS             1379
#define CHAN_HELP_CMD_REGISTER           1380
#define CHAN_HELP_CMD_IDENTIFY           1381
#define CHAN_HELP_CMD_SET                1382
#define CHAN_HELP_CMD_AOP                1383
#define CHAN_HELP_CMD_SOP                1384
#define CHAN_HELP_CMD_ACCESS             1385
#define CHAN_HELP_CMD_LEVELS             1386
#define CHAN_HELP_CMD_AKICK              1387
#define CHAN_HELP_CMD_DROP               1388
#define CHAN_HELP_CMD_SENDPASS           1389
#define CHAN_HELP_CMD_BAN                1390
#define CHAN_HELP_CMD_CLEAR              1391
#define CHAN_HELP_CMD_DEVOICE            1392
#define CHAN_HELP_CMD_GETKEY             1393
#define CHAN_HELP_CMD_INFO               1394
#define CHAN_HELP_CMD_INVITE             1395
#define CHAN_HELP_CMD_KICK               1396
#define CHAN_HELP_CMD_LIST               1397
#define CHAN_HELP_CMD_LOGOUT             1398
#define CHAN_HELP_CMD_OP                 1399
#define CHAN_HELP_CMD_TOPIC              1400
#define CHAN_HELP_CMD_UNBAN              1401
#define CHAN_HELP_CMD_VOICE              1402
#define CHAN_HELP_CMD_VOP                1403
#define CHAN_HELP_CMD_DEHALFOP           1404
#define CHAN_HELP_CMD_DEOWNER            1405
#define CHAN_HELP_CMD_DEPROTECT          1406
#define CHAN_HELP_CMD_HALFOP             1407
#define CHAN_HELP_CMD_HOP                1408
#define CHAN_HELP_CMD_OWNER              1409
#define CHAN_HELP_CMD_PROTECT            1410
#define CHAN_HELP_CMD_ADMIN              1411
#define CHAN_HELP_CMD_DEADMIN            1412
#define CHAN_HELP_CMD_DEOP               1413
#define CHAN_HELP                        1414
#define CHAN_HELP_EXPIRES                1415
#define CHAN_HELP_REGISTER               1416
#define CHAN_HELP_IDENTIFY               1417
#define CHAN_HELP_LOGOUT                 1418
#define CHAN_HELP_DROP                   1419
#define CHAN_HELP_SET                    1420
#define CHAN_HELP_SET_FOUNDER            1421
#define CHAN_HELP_SET_SUCCESSOR          1422
#define CHAN_HELP_SET_PASSWORD           1423
#define CHAN_HELP_SET_DESC               1424
#define CHAN_HELP_SET_URL                1425
#define CHAN_HELP_SET_EMAIL              1426
#define CHAN_HELP_SET_ENTRYMSG           1427
#define CHAN_HELP_SET_BANTYPE            1428
#define CHAN_HELP_SET_KEEPTOPIC          1429
#define CHAN_HELP_SET_TOPICLOCK          1430
#define CHAN_HELP_SET_MLOCK              1431
#define CHAN_HELP_SET_PEACE              1432
#define CHAN_HELP_SET_PRIVATE            1433
#define CHAN_HELP_SET_RESTRICTED         1434
#define CHAN_HELP_SET_SECURE             1435
#define CHAN_HELP_SET_SECUREOPS          1436
#define CHAN_HELP_SET_SECUREFOUNDER      1437
#define CHAN_HELP_SET_SIGNKICK           1438
#define CHAN_HELP_SET_XOP                1439
#define CHAN_HELP_SET_OPNOTICE           1440
#define CHAN_HELP_AOP                    1441
#define CHAN_HELP_HOP                    1442
#define CHAN_HELP_SOP                    1443
#define CHAN_HELP_VOP                    1444
#define CHAN_HELP_ACCESS                 1445
#define CHAN_HELP_ACCESS_LEVELS          1446
#define CHAN_HELP_AKICK                  1447
#define CHAN_HELP_LEVELS                 1448
#define CHAN_HELP_LEVELS_DESC            1449
#define CHAN_HELP_LEVELS_DESC_FORMAT     1450
#define CHAN_HELP_INFO                   1451
#define CHAN_HELP_LIST                   1452
#define CHAN_HELP_OP                     1453
#define CHAN_HELP_DEOP                   1454
#define CHAN_HELP_VOICE                  1455
#define CHAN_HELP_DEVOICE                1456
#define CHAN_HELP_HALFOP                 1457
#define CHAN_HELP_DEHALFOP               1458
#define CHAN_HELP_PROTECT                1459
#define CHAN_HELP_DEPROTECT              1460
#define CHAN_HELP_OWNER                  1461
#define CHAN_HELP_DEOWNER                1462
#define CHAN_HELP_INVITE                 1463
#define CHAN_HELP_UNBAN                  1464
#define CHAN_HELP_KICK                   1465
#define CHAN_HELP_BAN                    1466
#define CHAN_HELP_TOPIC                  1467
#define CHAN_HELP_CLEAR                  1468
#define CHAN_HELP_GETKEY                 1469
#define CHAN_HELP_SENDPASS               1470
#define CHAN_SERVADMIN_HELP              1471
#define CHAN_SERVADMIN_HELP_LOGOUT       1472
#define CHAN_SERVADMIN_HELP_DROP         1473
#define CHAN_SERVADMIN_HELP_SET          1474
#define CHAN_SERVADMIN_HELP_SET_NOEXPIRE 1475
#define CHAN_SERVADMIN_HELP_INFO         1476
#define CHAN_SERVADMIN_HELP_LIST         1477
#define CHAN_SERVADMIN_HELP_GETPASS      1478
#define CHAN_SERVADMIN_HELP_FORBID       1479
#define CHAN_SERVADMIN_HELP_SUSPEND      1480
#define CHAN_SERVADMIN_HELP_UNSUSPEND    1481
#define CHAN_SERVADMIN_HELP_STATUS       1482
#define MEMO_HELP_CMD_SEND               1483
#define MEMO_HELP_CMD_CANCEL             1484
#define MEMO_HELP_CMD_LIST               1485
#define MEMO_HELP_CMD_READ               1486
#define MEMO_HELP_CMD_DEL                1487
#define MEMO_HELP_CMD_SET                1488
#define MEMO_HELP_CMD_INFO               1489
#define MEMO_HELP_CMD_RSEND              1490
#define MEMO_HELP_CMD_CHECK              1491
#define MEMO_HELP_CMD_SENDALL            1492
#define MEMO_HELP_CMD_STAFF              1493
#define MEMO_HELP_HEADER                 1494
#define MEMO_HELP_ADMIN                  1495
#define MEMO_HELP_OPER                   1496
#define MEMO_HELP_FOOTER                 1497
#define MEMO_HELP_SEND                   1498
#define MEMO_HELP_CANCEL                 1499
#define MEMO_HELP_LIST                   1500
#define MEMO_HELP_READ                   1501
#define MEMO_HELP_DEL                    1502
#define MEMO_HELP_SET                    1503
#define MEMO_HELP_SET_NOTIFY             1504
#define MEMO_HELP_SET_LIMIT              1505
#define MEMO_HELP_INFO                   1506
#define MEMO_SERVADMIN_HELP_SET_LIMIT    1507
#define MEMO_SERVADMIN_HELP_INFO         1508
#define MEMO_HELP_STAFF                  1509
#define MEMO_HELP_SENDALL                1510
#define MEMO_HELP_RSEND                  1511
#define MEMO_HELP_CHECK                  1512
#define OPER_HELP_CMD_GLOBAL             1513
#define OPER_HELP_CMD_STATS              1514
#define OPER_HELP_CMD_OPER               1515
#define OPER_HELP_CMD_ADMIN              1516
#define OPER_HELP_CMD_STAFF              1517
#define OPER_HELP_CMD_MODE               1518
#define OPER_HELP_CMD_KICK               1519
#define OPER_HELP_CMD_CLEARMODES         1520
#define OPER_HELP_CMD_KILLCLONES         1521
#define OPER_HELP_CMD_AKILL              1522
#define OPER_HELP_CMD_SGLINE             1523
#define OPER_HELP_CMD_SQLINE             1524
#define OPER_HELP_CMD_SZLINE             1525
#define OPER_HELP_CMD_CHANLIST           1526
#define OPER_HELP_CMD_USERLIST           1527
#define OPER_HELP_CMD_LOGONNEWS          1528
#define OPER_HELP_CMD_RANDOMNEWS         1529
#define OPER_HELP_CMD_OPERNEWS           1530
#define OPER_HELP_CMD_SESSION            1531
#define OPER_HELP_CMD_EXCEPTION          1532
#define OPER_HELP_CMD_NOOP               1533
#define OPER_HELP_CMD_JUPE               1534
#define OPER_HELP_CMD_IGNORE             1535
#define OPER_HELP_CMD_SET                1536
#define OPER_HELP_CMD_RELOAD             1537
#define OPER_HELP_CMD_UPDATE             1538
#define OPER_HELP_CMD_RESTART            1539
#define OPER_HELP_CMD_QUIT               1540
#define OPER_HELP_CMD_SHUTDOWN           1541
#define OPER_HELP_CMD_DEFCON             1542
#define OPER_HELP_CMD_CHANKILL           1543
#define OPER_HELP_CMD_OLINE              1544
#define OPER_HELP_CMD_UMODE              1545
#define OPER_HELP_CMD_SVSNICK            1546
#define OPER_HELP_CMD_MODLOAD            1547
#define OPER_HELP_CMD_MODUNLOAD          1548
#define OPER_HELP_CMD_MODINFO            1549
#define OPER_HELP_CMD_MODLIST            1550
#define OPER_HELP                        1551
#define OPER_HELP_LOGGED                 1552
#define OPER_HELP_GLOBAL                 1553
#define OPER_HELP_STATS                  1554
#define OPER_HELP_OPER                   1555
#define OPER_HELP_ADMIN                  1556
#define OPER_HELP_IGNORE                 1557
#define OPER_HELP_MODE                   1558
#define OPER_HELP_UMODE                  1559
#define OPER_HELP_OLINE                  1560
#define OPER_HELP_CLEARMODES             1561
#define OPER_HELP_KICK                   1562
#define OPER_HELP_SVSNICK                1563
#define OPER_HELP_AKILL                  1564
#define OPER_HELP_SGLINE                 1565
#define OPER_HELP_SQLINE                 1566
#define OPER_HELP_SZLINE                 1567
#define OPER_HELP_SET                    1568
#define OPER_HELP_SET_READONLY           1569
#define OPER_HELP_SET_LOGCHAN            1570
#define OPER_HELP_SET_DEBUG              1571
#define OPER_HELP_SET_NOEXPIRE           1572
#define OPER_HELP_SET_SUPERADMIN         1573
#define OPER_HELP_SET_SQL                1574
#define OPER_HELP_SET_IGNORE             1575
#define OPER_HELP_SET_LIST               1576
#define OPER_HELP_NOOP                   1577
#define OPER_HELP_JUPE                   1578
#define OPER_HELP_RAW                    1579
#define OPER_HELP_UPDATE                 1580
#define OPER_HELP_RELOAD                 1581
#define OPER_HELP_QUIT                   1582
#define OPER_HELP_SHUTDOWN               1583
#define OPER_HELP_RESTART                1584
#define OPER_HELP_KILLCLONES             1585
#define OPER_HELP_CHANLIST               1586
#define OPER_HELP_USERLIST               1587
#define OPER_HELP_MODLOAD                1588
#define OPER_HELP_MODUNLOAD              1589
#define OPER_HELP_MODINFO                1590
#define OPER_HELP_MODLIST                1591
#define BOT_HELP_CMD_BOTLIST             1592
#define BOT_HELP_CMD_ASSIGN              1593
#define BOT_HELP_CMD_SET                 1594
#define BOT_HELP_CMD_KICK                1595
#define BOT_HELP_CMD_BADWORDS            1596
#define BOT_HELP_CMD_ACT                 1597
#define BOT_HELP_CMD_INFO                1598
#define BOT_HELP_CMD_SAY                 1599
#define BOT_HELP_CMD_UNASSIGN            1600
#define BOT_HELP_CMD_BOT                 1601
#define BOT_HELP                         1602
#define BOT_HELP_FOOTER                  1603
#define BOT_HELP_BOTLIST                 1604
#define BOT_HELP_ASSIGN                  1605
#define BOT_HELP_UNASSIGN                1606
#define BOT_HELP_INFO                    1607
#define BOT_HELP_SET                     1608
#define BOT_HELP_SET_DONTKICKOPS         1609
#define BOT_HELP_SET_DONTKICKVOICES      1610
#define BOT_HELP_SET_FANTASY             1611
#define BOT_HELP_SET_GREET               1612
#define BOT_HELP_SET_SYMBIOSIS           1613
#define BOT_HELP_KICK                    1614
#define BOT_HELP_KICK_BOLDS              1615
#define BOT_HELP_KICK_COLORS             1616
#define BOT_HELP_KICK_REVERSES           1617
#define BOT_HELP_KICK_UNDERLINES         1618
#define BOT_HELP_KICK_CAPS               1619
#define BOT_HELP_KICK_FLOOD              1620
#define BOT_HELP_KICK_REPEAT             1621
#define BOT_HELP_KICK_BADWORDS           1622
#define BOT_HELP_BADWORDS                1623
#define BOT_HELP_SAY                     1624
#define BOT_HELP_ACT                     1625
#define BOT_SERVADMIN_HELP_BOT           1626
#define BOT_SERVADMIN_HELP_SET           1627
#define BOT_SERVADMIN_HELP_SET_NOBOT     1628
#define BOT_SERVADMIN_HELP_SET_PRIVATE   1629
#define HOST_EMPTY                       1630
#define HOST_ENTRY                       1631
#define HOST_IDENT_ENTRY                 1632
#define HOST_SET                         1633
#define HOST_IDENT_SET                   1634
#define HOST_SETALL                      1635
#define HOST_DELALL                      1636
#define HOST_DELALL_SYNTAX               1637
#define HOST_IDENT_SETALL                1638
#define HOST_SET_ERROR                   1639
#define HOST_SET_IDENT_ERROR             1640
#define HOST_SET_TOOLONG                 1641
#define HOST_SET_IDENTTOOLONG            1642
#define HOST_NOREG                       1643
#define HOST_SET_SYNTAX                  1644
#define HOST_SETALL_SYNTAX               1645
#define HOST_DENIED                      1646
#define HOST_NOT_ASSIGNED                1647
#define HOST_ACTIVATED                   1648
#define HOST_IDENT_ACTIVATED             1649
#define HOST_ID                          1650
#define HOST_NOT_REGED                   1651
#define HOST_DEL                         1652
#define HOST_DEL_SYNTAX                  1653
#define HOST_OFF_UNREAL                  1654
#define HOST_NO_VIDENT                   1655
#define HOST_GROUP                       1656
#define HOST_IDENT_GROUP                 1657
#define HOST_LIST_FOOTER                 1658
#define HOST_LIST_RANGE_FOOTER           1659
#define HOST_LIST_KEY_FOOTER             1660
#define HOST_HELP_CMD_ON                 1661
#define HOST_HELP_CMD_OFF                1662
#define HOST_HELP_CMD_GROUP              1663
#define HOST_HELP_CMD_SET                1664
#define HOST_HELP_CMD_SETALL             1665
#define HOST_HELP_CMD_DEL                1666
#define HOST_HELP_CMD_DELALL             1667
#define HOST_HELP_CMD_LIST               1668
#define HOST_OPER_HELP                   1669
#define HOST_ADMIN_HELP                  1670
#define HOST_HELP                        1671
#define HOST_HELP_ON                     1672
#define HOST_HELP_SET                    1673
#define HOST_HELP_DELALL                 1674
#define HOST_HELP_SETALL                 1675
#define HOST_HELP_OFF                    1676
#define HOST_HELP_DEL                    1677
#define HOST_HELP_LIST                   1678
#define HOST_HELP_GROUP                  1679
#define OPER_SVSNICK_UNSUPPORTED         1680
#define OPER_SQLINE_UNSUPPORTED          1681
#define OPER_SVSO_UNSUPPORTED            1682
#define OPER_UMODE_UNSUPPORTED           1683
#define OPER_SUPER_ADMIN_NOT_ENABLED     1684

#define NUM_STRINGS 1685
