/**
 * Language variables and headers for filling
 *
 ***********
 * Module Name    : bs_fantasy_ext
 * Author         : Viper <Viper@Absurd-IRC.net>
 * Creation Date  : 21/07/2006
 *
 * More info on http://modules.anope.org and http://forum.anope.org
 ***********
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 ***********
 *
 * Last Updated   : 03/04/2008
 *
 **/

void add_languages(void);

#define LANG_NUM_STRINGS 					194

#define LANG_HELP							0
#define LANG_CLEAR_SYNTAX					1
#define LANG_EXCEPTS_UNSUPPORTED			2
#define LANG_INVITEMODE_UNSUPPORTED			3
#define LANG_HOPS_UNSUPPORTED				4
#define LANG_SOP_SYNTAX						5
#define LANG_SOP_SYNTAX_EXT					6
#define LANG_AOP_SYNTAX						7
#define LANG_AOP_SYNTAX_EXT					8
#define LANG_HOP_SYNTAX						9
#define LANG_HOP_SYNTAX_EXT					10
#define LANG_VOP_SYNTAX						11
#define LANG_VOP_SYNTAX_EXT					12
#define LANG_ACCESS_SYNTAX					13
#define LANG_ACCESS_SYNTAX_EXT				14
#define LANG_LEVELS_SYNTAX					15
#define LANG_LEVELS_SYNTAX_EXT				16
#define LANG_LEVELS_ERR_NO_VAL				17
#define LANG_LEVELS_ERR_VAL					18
#define LANG_ONLY_FOUNDERS					19
#define LANG_GOLIST_OPER_ONLY				20
#define LANG_GOLIST_OPER_AND_SO				21
#define LANG_GOLIST_OPER_AND_SA				22
#define LANG_GOLIST_OPER_AND_SRA			23
#define LANG_GOLIST_NONE					24
#define LANG_GOLIST_HEADER					25
#define LANG_GOLIST_FOOTER					26
#define LANG_AKICK_SYNTAX					27
#define LANG_AKICK_SYNTAX_EXT				28
#define LANG_BADWORDS_SYNTAX				29
#define LANG_BADWORDS_SYNTAX_EXT			30
#define LANG_BADWORDS_ERR_STYLE				31
#define LANG_CMD_NOT_AV						32
#define LANG_SET_SYNTAX						33
#define LANG_SET_SYNTAX_EXT					34
#define LANG_SET_FOUNDER_SYNTAX				35
#define LANG_SET_FOUNDER_SYNTAX_EXT			36
#define LANG_SET_SUCCESSOR_SYNTAX			37
#define LANG_SET_SUCCESSOR_SYNTAX_EXT		38
#define LANG_SET_DESC_SYNTAX				39
#define LANG_SET_DESC_SYNTAX_EXT			40
#define LANG_SET_URL_SYNTAX					41
#define LANG_SET_URL_SYNTAX_EXT				42
#define LANG_SET_EMAIL_SYNTAX				43
#define LANG_SET_EMAIL_SYNTAX_EXT			44
#define LANG_SET_ENTRYMSG_SYNTAX			45
#define LANG_SET_ENTRYMSG_SYNTAX_EXT		46
#define LANG_SET_BANTYPE_SYNTAX				47
#define LANG_SET_BANTYPE_SYNTAX_EXT			48
#define LANG_SET_MLOCK_SYNTAX				49
#define LANG_SET_MLOCK_SYNTAX_EXT			50
#define LANG_SET_KEEPTOPIC_SYNTAX			51
#define LANG_SET_KEEPTOPIC_SYNTAX_EXT		52
#define LANG_SET_TOPICLOCK_SYNTAX			53
#define LANG_SET_TOPICLOCK_SYNTAX_EXT		54
#define LANG_SET_OPNOTICE_SYNTAX			55
#define LANG_SET_OPNOTICE_SYNTAX_EXT		56
#define LANG_SET_PEACE_SYNTAX				57
#define LANG_SET_PEACE_SYNTAX_EXT			58
#define LANG_SET_PRIVATE_SYNTAX				59
#define LANG_SET_PRIVATE_SYNTAX_EXT			60
#define LANG_SET_RESTRICTED_SYNTAX			61
#define LANG_SET_RESTRICTED_SYNTAX_EXT		62
#define LANG_SET_SECURE_SYNTAX				63
#define LANG_SET_SECURE_SYNTAX_EXT			64
#define LANG_SET_SECUREOPS_SYNTAX			65
#define LANG_SET_SECUREOPS_SYNTAX_EXT		66
#define LANG_SET_SECUREFOUNDER_SYNTAX		67
#define LANG_SET_SECUREFOUNDER_SYNTAX_EXT	68
#define LANG_SET_SIGNKICK_SYNTAX			69
#define LANG_SET_SIGNKICK_SYNTAX_EXT		70
#define LANG_SET_XOP_SYNTAX					71
#define LANG_SET_XOP_SYNTAX_EXT				72
#define LANG_SET_NOEXPIRE_SYNTAX			73
#define LANG_SET_NOEXPIRE_SYNTAX_EXT		74
#define LANG_TOPIC_SYNTAX					75
#define LANG_TOPIC_SYNTAX_EXT				76
#define LANG_INVITE_SYNTAX					77
#define LANG_INVITE_SYNTAX_EXT				78
#define LANG_INVITE_NO_USER					79
#define LANG_INVITE_IS_ON					80
#define LANG_INVITE_YOURSELF				81
#define LANG_CMD_LIST_HEADER				82
#define LANG_CMD_LIST_FOOTER				83
#define LANG_CMD_LIST_GENERAL				84
#define LANG_CMD_LIST_CHAN_AXX				85
#define LANG_CMD_LIST_CHG_SET				86
#define LANG_CMD_LIST_ACTIONS				87
#define LANG_CMD_LIST_IRCOP					88
#define LANG_UNKNOWN_CMD					89
#define LANG_HELP_HEADER					90
#define LANG_HELP_FOOTER					91
#define LANG_APPENDTOPIC_SYNTAX				92
#define LANG_APPENDTOPIC_SYNTAX_EXT			93
#define LANG_STAFF							94
#define LANG_CMDLIST						95
#define LANG_MINFO							96
#define LANG_HELP_UNKNOWN_CMD				97
#define LANG_BAN_SYNTAX						98
#define LANG_BAN_SYNTAX_EXT					99
#define LANG_MUTE_SYNTAX					100
#define LANG_MUTE_SYNTAX_EXT				101
#define LANG_UNMUTE_SYNTAX					102
#define LANG_UNMUTE_SYNTAX_EXT				103
#define LANG_SVERSION						104
#define LANG_KILL_SYNTAX					105
#define LANG_KILL_SYNTAX_EXT				106
#define LANG_MODE_SYNTAX					107
#define LANG_MODE_SYNTAX_EXT				108
#define LANG_AKILL_SYNTAX					109
#define LANG_AKILL_SYNTAX_EXT				110
#define LANG_IGNORE_SYNTAX					111
#define LANG_IGNORE_SYNTAX_EXT				112
#define LANG_INFO_SYNTAX					113
#define LANG_INFO_SYNTAX_EXT				114
#define LANG_CMD_DISABLED					115
#define LANG_HELP_CMDS_GEN					116
#define LANG_HELP_CMDS_ACC					117
#define LANG_HELP_CMDS_SETTINGS				118
#define LANG_HELP_CMDS_ACTIONS				119
#define LANG_HELP_CMDS_PUTMODES				120
#define LANG_HELP_CMDS_IRCOP				121
#define LANG_HELP_MORE_INFO					122
#define LANG_HELP_LIST						123
#define LANG_SET_DONTKICKOPS_SYNTAX			124
#define LANG_SET_DONTKICKOPS_SYNTAX_EXT		125
#define LANG_SET_DONTKICKVOICES_SYNTAX		126
#define LANG_SET_DONTKICKVOICES_SYNTAX_EXT	127
#define LANG_SET_GREET_SYNTAX				128
#define LANG_SET_GREET_SYNTAX_EXT			129
#define LANG_SET_FANTASY_SYNTAX				130
#define LANG_SET_FANTASY_SYNTAX_EXT			131
#define LANG_SET_SYMBIOSIS_SYNTAX			132
#define LANG_SET_SYMBIOSIS_SYNTAX_EXT		133
#define LANG_SET_NOBOT_SYNTAX				134
#define LANG_SET_NOBOT_SYNTAX_EXT			135
#define LANG_BKICK_SYNTAX					136
#define LANG_BKICK_SYNTAX_EXT				137
#define LANG_BKICK_BOLDS_SYNTAX				138
#define LANG_BKICK_BOLDS_SYNTAX_EXT			139
#define LANG_BKICK_BADWORDS_SYNTAX			140
#define LANG_BKICK_BADWORDS_SYNTAX_EXT		141
#define LANG_BKICK_CAPS_SYNTAX				142
#define LANG_BKICK_CAPS_SYNTAX_EXT			143
#define LANG_BKICK_COLORS_SYNTAX			144
#define LANG_BKICK_COLORS_SYNTAX_EXT		145
#define LANG_BKICK_FLOOD_SYNTAX				146
#define LANG_BKICK_FLOOD_SYNTAX_EXT			147
#define LANG_BKICK_REPEAT_SYNTAX			148
#define LANG_BKICK_REPEAT_SYNTAX_EXT		149
#define LANG_BKICK_REVERSES_SYNTAX			150
#define LANG_BKICK_REVERSES_SYNTAX_EXT		151
#define LANG_BKICK_UNDERLINES_SYNTAX		152
#define LANG_BKICK_UNDERLINES_SYNTAX_EXT	153
#define LANG_BKICK_UNKNOWN_OPTION			154
#define LANG_ADLIST_SA						155
#define LANG_ADLIST_SRA						156
#define LANG_ADLIST_NONE					157
#define LANG_ADLIST_HEADER					158
#define LANG_ADLIST_FOOTER					159
#define LANG_KICKBAN_SYNTAX					160
#define LANG_KICKBAN_SYNTAX_EXT				161
#define LANG_UP_SYNTAX						162
#define LANG_UP_SYNTAX_EXT					163
#define LANG_DOWN_SYNTAX					164
#define LANG_DOWN_SYNTAX_EXT				165
#define LANG_UPDOWN_SYNTAX					166
#define LANG_TBAN_SYNTAX					167
#define LANG_TBAN_SYNTAX_EXT				168
#define LANG_TBAN_RESPONSE					169
#define LANG_TKBAN_SYNTAX					170
#define LANG_TKBAN_SYNTAX_EXT				171
#define LANG_INVALID_TIME					172
#define LANG_REQ_NICK_OR_MASK				173
#define LANG_SUSPEND_SYNTAX					174
#define LANG_SUSPEND_SYNTAX_EXT				175
#define LANG_SUSPEND_NO_REASON				176
#define LANG_KB_KICK_DENIED					177
#define LANG_CLEAR_SYNTAX_EXT				178
#define LANG_ACCESS_LEVELS					179
#define LANG_ADMINS							180
#define LANG_SYNC_SYNTAX					181
#define LANG_SYNC_SYNTAX_EXT				182
#define LANG_SYNC_DONE						183
#define LANG_SHUN_SYNTAX					184
#define LANG_SHUN_SYNTAX_EXT				185
#define LANG_TSHUN_SYNTAX					186
#define LANG_TSHUN_SYNTAX_EXT				187
#define LANG_SHUN_ADDED						188
#define LANG_SHUN_DELETION					189
#define LANG_TSHUN_ADDED					190
#define LANG_TSHUN_DELETION					191
#define LANG_TSHUN_TARGET_NEXIST			192
#define LANG_TSHUN_TARGET_OPER				193


/* Language Variables */
int xop_msgs[4][14] = {
	{	CHAN_AOP_SYNTAX, CHAN_AOP_DISABLED, CHAN_AOP_NICKS_ONLY, CHAN_AOP_ADDED, CHAN_AOP_MOVED,
		CHAN_AOP_NO_SUCH_ENTRY, CHAN_AOP_NOT_FOUND, CHAN_AOP_NO_MATCH, CHAN_AOP_DELETED, CHAN_AOP_DELETED_ONE,
		CHAN_AOP_DELETED_SEVERAL, CHAN_AOP_LIST_EMPTY, CHAN_AOP_LIST_HEADER, CHAN_AOP_CLEAR
	},
	{	CHAN_SOP_SYNTAX, CHAN_SOP_DISABLED, CHAN_SOP_NICKS_ONLY, CHAN_SOP_ADDED, CHAN_SOP_MOVED,
		CHAN_SOP_NO_SUCH_ENTRY, CHAN_SOP_NOT_FOUND, CHAN_SOP_NO_MATCH, CHAN_SOP_DELETED, CHAN_SOP_DELETED_ONE,
		CHAN_SOP_DELETED_SEVERAL, CHAN_SOP_LIST_EMPTY, CHAN_SOP_LIST_HEADER, CHAN_SOP_CLEAR
	},
	{	CHAN_VOP_SYNTAX, CHAN_VOP_DISABLED, CHAN_VOP_NICKS_ONLY, CHAN_VOP_ADDED, CHAN_VOP_MOVED,
		CHAN_VOP_NO_SUCH_ENTRY, CHAN_VOP_NOT_FOUND, CHAN_VOP_NO_MATCH, CHAN_VOP_DELETED, CHAN_VOP_DELETED_ONE,
		CHAN_VOP_DELETED_SEVERAL, CHAN_VOP_LIST_EMPTY, CHAN_VOP_LIST_HEADER, CHAN_VOP_CLEAR
	},
	{	CHAN_HOP_SYNTAX, CHAN_HOP_DISABLED, CHAN_HOP_NICKS_ONLY, CHAN_HOP_ADDED, CHAN_HOP_MOVED,
		CHAN_HOP_NO_SUCH_ENTRY, CHAN_HOP_NOT_FOUND, CHAN_HOP_NO_MATCH, CHAN_HOP_DELETED, CHAN_HOP_DELETED_ONE,
		CHAN_HOP_DELETED_SEVERAL, CHAN_HOP_LIST_EMPTY, CHAN_HOP_LIST_HEADER, CHAN_HOP_CLEAR
	}
};


/* EOF */
